<?php
/*
#------------------------------------------------------------------------
  Magento Extension - OnSale Product Horizontal Carousel
#------------------------------------------------------------------------
# Copyright (C) 2012 VJ Templates.
# @license - GNU/GPL
# Author: VJ Templates
# Websites: http://www.vjtemplates.com
#------------------------------------------------------------------------
*/
?>
<?php
    $_productCollection=$this->getOnSaleProduct();
    $_helper = $this->helper('catalog/output');
	$this->setData('column_count',2);
?>
<div class="category-products">
<h1><?php echo $this->__('On Sale Products') ?></h1>
<ul id="vjt-onsale-horz-carousel" class="jcarousel-skin-vjt-onsale-horz">

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
            <li>
            <a href="<?php echo $_product->getProductUrl() ?>" rel="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(400,300); ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image preview"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(120); ?>" width="120" height="120" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </li>
        <?php endforeach ?>
</ul>
</div>
