<?php	
	$importCategoryTotal = Mage::getSingleton('core/session')->getimportCategoryTotal();
	$importProductsTotal = Mage::getSingleton('core/session')->getimportProductsTotal();
	$importCustomersTotal = Mage::getSingleton('core/session')->getimportCustomersTotal();
	$importOrdersTotal = Mage::getSingleton('core/session')->getimportOrdersTotal();
	
	$error_msg = Mage::getSingleton('core/session')->getErrorMSG(); 		
?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center"><h1><strong>osCommerce Products/Categories/Customers/Orders Import </strong></h1></td>
  </tr>
  <tr>
    <td><strong>Step 3. Preparing TMP Tables</strong></td>
  </tr>
  <tr>
    <td><br /><br />
</td>
  </tr>
	<?php if ($error_msg != ''){?>
  <tr>
    <td class="error"><hr /><h1><strong>ERROR</strong></h1><?php echo $error_msg; ?><hr /></td>
  </tr>    
  <?php } ?>   
  <tr>
    <td>We will go to conect to the oscommerce database and read all the products id and categories id and save the information in the tmp tables</td>
  </tr>
  <tr>
    <td><br />
      <strong>Total Categories to import:</strong> <?php echo $importCategoryTotal; ?><br />
      <strong>Total Products to import:</strong> <?php echo $importProductsTotal; ?><br />
      <strong>Total Customerts to import:</strong> <?php echo $importCustomersTotal; ?><br />
      <strong>Total Orders to import:</strong> <?php echo $importOrdersTotal; ?><br /></td>
  </tr>
  <tr>
    <td><br />
    <br />
    <br />    <div align="center"><a href="<?php echo $this->getUrl('oscommerceimport')?>">Main Menu</a></div></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><div align="center">Powered by <a href="http://www.ezmage.com/" target="_blank">ezMage</a> - We provide Magento Support 702-485-3332</div></td>
  </tr>
</table>
