<?php
		$truncate_tables = Mage::registry('truncate_tables');
?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center"><h1><strong>osCommerce Products/Categories/Customers/Orders Import </strong></h1></td>
  </tr>
  <tr>
    <td><strong>Step 2. Create TMP Tables</strong></td>
  </tr>
  <tr>
    <td><br /><br />
</td>
  </tr>
  <tr>
    <td>TMP tables: <em>ezmage_categories, ezmage_products, ezmage_customers, ezmage_orders, ezmage_log </em>have been created</td>
  </tr>
  <tr>
    <td><br />
      If you want to delete this tables run this sql <br />
<br />
drop table ezmage_categories;<br />
drop table ezmage_log;<br />
drop table ezmage_products; <br />
drop table ezmage_customers; <br />
drop table ezmage_orders; </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>If you want to clean the tmp tables please <a href="<?php echo $this->getUrl('oscommerceimport/index/step21/')?>">click here</a><br />
<?php if ($truncate_tables == 'yes'){?>      
      <br />
      <br />
      The tmp have been truncated
<?php } ?>      
    </td>
  </tr>
  <tr>
    <td><br />
    <br />
    <br />    <div align="center"><a href="<?php echo $this->getUrl('oscommerceimport')?>">Main Menu</a></div></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><div align="center">Powered by <a href="http://www.ezmage.com/" target="_blank">ezMage</a> - We provide Magento Support 702-485-3332</div></td>
  </tr>
</table>
