<style>
.highslide-maincontent {
    display: none;
}
</style> 
<FORM  id="measure" name="measure" method="post" action="sdconfirm.php" onsubmit="return validate(document.measure);">
		<table class="ProdListingMain" cellpadding="0" cellspacing="0" >
        <tr>
          <td class="breadcrumb"><a href="http://www.sareez.com/index.php">Home</a> &raquo; <span>Measurement</span> </td>
        </tr>
			<tr>
				<td align="center">
					<table cellpadding="0" cellspacing="0" class="address_book_heading">
						<tr>
							<td width="544" class="address_book_heading"><strong>Custom-make to your size</strong></td>
							<td width="179" class="accOdrStat">&nbsp;</td>
						</tr>
					</table>
										<table cellpadding="0" cellspacing="0" class="address_book_heading">
                      <tr>
                        <td width="544" class="address_book_heading"><strong>Instructions</strong></td>
                        <td width="179" class="accOdrStat">&nbsp;</td>
                      </tr>
                    </table>
					<table width="680" border="0" cellspacing="0" cellpadding="0" class="address_book_text">
                      <INPUT type="hidden" name="products_id" value="0{3}2{4}1">
                      <INPUT type="hidden" id="measurement_id" name="measurement_id" value="">
                      <INPUT type="hidden" id="meopt" name="meopt" value="Blouse-Petticoat">
					  <INPUT type="hidden" id="page" name="page" value="">
					  <INPUT type="hidden" id="order_id" name="order_id" value="">

                      <tr>
                        <td width="26" align="center" valign="middle"><img src="http://static.sareez.com/images/arrrowBox.jpg" width="5" height="5" /></td>
                        <td height="40" align="left" valign="middle">Your specification of sizes and styles are subject to the kind of fabric and limitations. Our expert designers' team might not find all your selections practically suitable. In such cases you might be intimated to select some other style compatible with the fabric.                                                     </td>
                      </tr>
                      <tr>
                        <td align="center" valign="middle"><img src="http://static.sareez.com/images/arrrowBox.jpg" width="5" height="5" /></td>
                        <td height="40" align="left" valign="middle"><span class="carttext" style="text-align:justify;padding-right:10px;">In cases where certain extreme values have been put in the measurement form, we usually try to round them off. But we can attempt exact measurements on special requests.</span></td>
                      </tr>
                      <tr>
                        <td align="center" valign="middle"><img src="http://static.sareez.com/images/arrrowBox.jpg" width="5" height="5" /></td>
                        <td height="40" align="left" valign="middle"><span class="carttext" style="text-align:justify;padding-right:10px;">In case of any major issue regarding cost or any extra charge estimated by our team of designers, you would be contacted for your choice or opinion.</span></td>
                      </tr>
                      <tr>
                        <td align="center" valign="middle"><img src="http://static.sareez.com/images/arrrowBox.jpg" width="5" height="5" /></td>
                        <td height="40" align="left" valign="top"><span class="carttext" style="text-align:justify;padding-right:10px;">In case of any discrepancy or confusion regarding the measurement values we will get back to you for clarification. If we are unable to contact you within 7 days or there is no response from your end, then we would have to depend on the experience and judgement of our experts' team. We would not be liable to re-tailor the dress on further requests made by you.</span></td>
                      </tr>
                      <tr>
                        <td align="center" valign="middle"><img src="http://static.sareez.com/images/arrrowBox.jpg" width="5" height="5" /></td>
                        <td height="40" align="left" valign="middle"><span class="carttext" style="text-align:justify;padding-right:10px;">We also accept specimen clothes that fit you the best. The best-fit specimen can be sent to us so that we could work with confidence and perfection. The said specimen shall be returned to you along with the new garment.</span></td>
                      </tr>
                      <!--<tr>
                        <td align="center" valign="middle">&nbsp;</td>
                        <td height="20" align="left" valign="top"><span class="carttext" style="text-align:justify;padding-right:10px;">you.</span></td>
                      </tr>
                      <tr>
                        <td align="center" valign="middle"><img src="images/arrrowBox.jpg" width="5" height="5" /></td>
                        <td height="20" align="left" valign="middle"><span class="carttext" style="text-align:justify;padding-right:10px;">The formula to convert inches to centimeters : 1 inch = 2.54 cm. i.e. 10 inches = 10 x 2.54 = 25.4cm.  &amp;  10 cm equals 3.9 </span></td>
                      </tr>
                      <tr>
                        <td align="center" valign="middle">&nbsp;</td>
                        <td height="20" align="left" valign="top"><span class="carttext" style="text-align:justify;padding-right:10px;">inches.</span></td>
                      </tr>
                      -->
                      <tr>
                        <td align="center" valign="middle"><img src="http://static.sareez.com/images/arrrowBox.jpg" width="5" height="5" /></td>
                        <td height="30" align="left" valign="middle">For any queries or assistance mail us at <a href="mailto:measurement@sareez.com" class="email">measurement@sareez.com</a>.</td>
                      </tr>
					  <tr>
                        <td align="center" valign="middle">&nbsp;</td>
                        <td height="30" align="left" valign="middle"><strong>USEFUL CONVERSIONS:</strong></td>
                      </tr>
                      <tr>
                        <td align="center" valign="middle">&nbsp;</td>
                        <td height="16" align="left" valign="top"><span class="carttext" style="text-align:justify;padding-right:10px;">1 inch = 2.54 cm. </span></td>
                      </tr>
					  <tr>
                        <td align="center" valign="middle">&nbsp;</td>
                        <td height="16" align="left" valign="top"><span class="carttext" style="text-align:justify;padding-right:10px;">10 cm = 3.9 inches    or    100 cm = 1 metre = 39 inches</span></td>
                      </tr>
                      <!--<tr>
                        <td align="center" valign="middle"><img src="images/arrrowBox.jpg" width="5" height="5" /></td>
                        <td height="20" align="left" valign="middle" class="redText"><a href="javascript:MM_openBrWindow('best_fit_guide.html','Customization','scrollbars=yes,width=640,height=650');"><b>Click here to view guide to best fit</b></a></td>
                      </tr>-->
                      <tr>
                        <td align="center" valign="middle"><img src="http://static.sareez.com/images/arrrowBox.jpg" width="5" height="5" /></td>
                        <td height="20" align="left" valign="middle" class="redText">
<a class="redText" href="index.htm" onclick="return hs.htmlExpand(this, { headingText: 'Create new using previous measurement' })"> <b>Click here to create new using previous measurement </b>&nbsp;<img src="http://static.sareez.com/images/search_style_btn.jpg" title="Previos Measurements"  style="cursor:pointer; margin-top:3px;" height="18" width="19"></a>
								  
								  
								  <div class="highslide-maincontent">
								  <div class="area1">
								    <table width="580" border="1" cellspacing="0" cellpadding="0" class="popup1">
									<tr>
									  <td width="290" align="left" valign="top"><table width="280" border="0" cellspacing="0" cellpadding="0">
																			  </table>
									  </td>
									  <td width="290" align="left" valign="top" class="popup1_left">
									  <p class="heading_text"><strong>Previous Measurement(s) for Saree</strong></p>
									  <br />
									  <p class="text" align="left">The left column contains &quot;Previous Measurement(s) for Saree&quot;. Choose the measurement and click on the &quot;Set Measurement&quot; button to populate the measurement. You can edit on this measurement by not changing the measurement name OR save a new measurement with new measurement name using the this measurement information. </p><br />
									  <img src="http://static.sareez.com/includes/languages/english/images/buttons/set_measurement_btn.jpg" style="cursor:pointer;" onClick="set_measurement_id('');return hs.close(this)" border="0" alt="Set Measurement"><br />
									  <p class="heading_text">&nbsp;</p>
									  </td>
									</tr>
								  </table>
								  </div>
								</div>
					  	</td>
					  </tr>
                    </table>
					
					<table width="704" border="0" cellpadding="0" cellspacing="0" class="address_book_text">
                      <tr>
                        <td align="left" valign="middle" class="form_area_heading"><img src="http://static.sareez.com/images/form_arrow.jpg" />&nbsp;&nbsp;<strong>Your Information</strong></td>
                        <td align="center" valign="top" class="form_area_heading">&nbsp;</td>
                        <td width="514" colspan="2" align="right" valign="middle" class="form_area_heading1">[ <span class="redText">*</span> marked fields are mandatory ]</td>
                      </tr>
                      <tr>
                        <td align="right" valign="top">&nbsp;</td>
                        <td align="center" valign="top">&nbsp;</td>
                        <td colspan="2" align="left" valign="top">&nbsp;</td>
                      </tr>
					                       <tr>
                        <td width="171" align="right" valign="top">Full Name <span class="redText">*</span></td>
                        <td width="19" align="center" valign="top">:</td>
                        <td colspan="2" align="left" valign="top"><input type="text" name="fname" id="fname" size="30" class="input_area" value="Akhilesh Tiwary" readonly="readonly" /></td>
                      </tr>
                      <tr>
                        <td align="right" valign="top" class="form_divider">&nbsp;</td>
                        <td align="center" valign="top" class="form_divider">&nbsp;</td>
                        <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                      </tr>
                      <tr>
                        <td align="right" valign="top">Email Id <span class="redText">*</span></td>
                        <td align="center" valign="top">:</td>
                        <td colspan="2" align="left" valign="top"><input type="text" name="email" id="email" class="input_area" size="30" value="akhilesh@indusnet.co.in" readonly="readonly" /></td>
                      </tr>
                                                    <tr>
                        <td align="right" valign="top" class="form_divider">&nbsp;</td>
                        <td align="center" valign="top" class="form_divider">&nbsp;</td>
                        <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                      </tr>
                      <tr>
                        <td width="171" align="right" valign="top">Measurement Name <span class="redText">*</span></td>
                        <td width="19" align="center" valign="top">:</td>
                        <td colspan="2" align="left" valign="top" class="form_small_ass"><input type="text" name="measurement_name" id="measurement_name" size="30" class="input_area" value="" />&nbsp; </td>
                      </tr>
                      
					  <tr>
                        <td width="171" align="right" valign="top">&nbsp;</td>
                        <td width="19" align="center" valign="top">&nbsp;</td>
                        <td colspan="2" align="left" valign="top" class="form_small_ass">
						( Your measurement will be saved with this keyword, which will be helpful to you later / next<br /> time you fill in the measurement form. Example. Mom Measurement, Sister etc. )						</td>
                      </tr>
                      <!--<tr>
                        <td align="right" valign="top" class="form_divider">&nbsp;</td>
                        <td align="center" valign="top" class="form_divider">&nbsp;</td>
                        <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                      </tr>
                      <tr>
                        <td align="left" valign="middle" class="form_area_heading"><img src="images/form_arrow.jpg" />&nbsp;&nbsp;<strong>Measurement in inches</strong></td>
                        <td align="center" valign="top" class="form_area_heading">&nbsp;</td>
                        <td colspan="2" align="right" valign="middle" class="form_area_heading1"></td>
                      </tr>-->
<!--                      <tr>
                        <td align="right" valign="top">&nbsp;</td>
                        <td align="center" valign="top">&nbsp;</td>
                        <td colspan="2" align="left" valign="top">&nbsp;</td>
                      </tr>
                      <tr>
                        <td width="171" align="right" valign="top">Measurement in <span class="redText">*</span></td>
                        <td width="19" align="center" valign="top">:</td>
                        <td colspan="2" align="left" valign="top"><table width="341" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td width="27" align="left" valign="middle"><input name="radiobutton" type="radio" value="radiobutton" /></td>
                            <td width="66" align="left" valign="middle">Inches</td>
                            <td width="28" align="left" valign="middle"><input name="radiobutton" type="radio" value="radiobutton" /></td>
                            <td width="220" align="left" valign="middle">Centemeters</td>
                          </tr>
                        </table></td>
                      </tr>
-->                      <tr>
                        <td align="right" valign="top" class="form_divider">&nbsp;</td>
                        <td align="center" valign="top" class="form_divider">&nbsp;</td>
                        <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                      </tr>
                      <tr>
                        <td align="left" valign="middle" class="form_area_heading"><img src="images/form_arrow.jpg" />&nbsp;&nbsp;<strong>Measurement For</strong></td>
                        <td align="center" valign="top" class="form_area_heading">&nbsp;</td>
                        <td colspan="2" align="right" valign="middle" class="form_area_heading1"></td>
                      </tr>
                      <tr>
                        <td align="right" valign="top">&nbsp;</td>
                        <td align="center" valign="top">&nbsp;</td>
                        <td colspan="2" align="left" valign="top">&nbsp;</td>
                      </tr>
                      <tr>
                        <td width="171" align="right" valign="top">Body <span class="redText">&nbsp;</span></td>
                        <td width="19" align="center" valign="top">:</td>
                        <td colspan="2" align="left" valign="top"><input name="body_garment" type="radio" value="body" checked/></td>
                      </tr>
					  <tr>
                        <td width="171" align="right" valign="top"><span class="redText">&nbsp;</span></td>
                        <td width="19" align="center" valign="top">&nbsp;</td>
                        <td colspan="2" align="left" valign="top" class="form_small_ass">(You want to submit your body measurement and our tailor will give suitable loosening as per tailoring)</td>
					  </tr>
					  <tr>
                        <td align="right" valign="top" class="form_divider">&nbsp;</td>
                        <td align="center" valign="top" class="form_divider">&nbsp;</td>
                        <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                      </tr>
                      <tr>
					  <tr>
                        <td width="171" align="right" valign="top">Garment <span class="redText">&nbsp;</span></td>
                        <td width="19" align="center" valign="top">:</td>
                        <td colspan="2" align="left" valign="top"><input name="body_garment" type="radio" value="garment"  /></td>
                      </tr>
					  <tr>
                        <td width="171" align="right" valign="top"><span class="redText">&nbsp;</span></td>
                        <td width="19" align="center" valign="top">&nbsp;</td>
                        <td colspan="2" align="left" valign="top" class="form_small_ass">(If you want to submit ready garment measurement)</td>
					  </tr>
                      
                      
					  
                      <tr> </tr>
                    </table>
					
					
					<table width="706" border="0" cellpadding="0" cellspacing="0" class="address_book_text">
                      
                      <tr>
                        <td width="318" align="left" valign="middle" class="form_area_heading"><img src="http://static.sareez.com/images/form_arrow.jpg" />&nbsp;&nbsp;<strong>Measurement</strong></td>
                        <td  colspan="2" align="right" valign="middle" class="form_area_heading1">[ <span class="redText">*</span> marked fields are mandatory ]</td>
                      </tr>
                      <tr>
                        <td colspan="3" align="left" valign="top"><table width="700" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td width="167">&nbsp;</td>
                            <td width="20">&nbsp;</td>
                            <td width="320">&nbsp;</td>
                            <td width="5">&nbsp;</td>
                          </tr>
						  
						  						  
						  <tr>
                            <td align="right" valign="top">1. Around Bust <span class="redText">*</span></td>
                            <td align="center" valign="top">:</td>
                            <td colspan="2" align="left" valign="top" class="form_small_ass">
							<SELECT class="select_box" name="around_bust" id="around_bust" style="width:70px;" onChange="">
								<OPTION value="" <?php if($around_bust==''){ ?>selected="selected" <?php } ?>>Select</OPTION>
                                                                 <?php
								  for($i=25 ;$i<=70;$i=$i+(1/2)){
								  ?>
                                 <OPTION value="<?php echo $i ?>" <?php if($around_bust==$i){ ?>selected="selected" <?php } ?>><?php echo $i ?></OPTION>
                                 <?php } ?>
                                </SELECT>
                              &nbsp;in Inches &nbsp;
							  <img id="AB" src="http://static.sareez.com/images/help_icon.jpg" style="cursor:pointer" alt="Help" border="0" title="Help" onclick="return hs.htmlExpand(this, { headingText: 'Around Bust' })" />
							  
							  <div class="highslide-maincontent"><div class="area1"> 
								 <table width="580" border="0" cellspacing="0" cellpadding="0" class="popup1">
									<tr>
									  <td width="360" align="left" valign="top" class="popup1_right"><img src="http://static.sareez.com/images/utsav/around_bust.jpg" /></td>
									  <td width="220" align="left" valign="top" class="popup1_left">
									  <p class="heading_text"><strong>How to measure "Around Bust" ?</strong></p>
									  <p class="text">Fullest part of the bust is to be measured by placing the tape well under the arms winding straight across the back and coming back to the front.</p></td>
									</tr>
								  </table>							  
							  </div></div>
							  </td>
                            <td width="188" rowspan="34" align="center" valign="top"><img src="http://static.sareez.com/images/body_img1.jpg" width="174" height="327" /><img src="http://static.sareez.com/images/body_img2.jpg" width="146" height="371" /></td>
                          </tr>
						  						  
                          <tr>
                            <td align="right" valign="top" class="form_divider">&nbsp;</td>
                            <td align="center" valign="top" class="form_divider">&nbsp;</td>
                            <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                          </tr>
						  
						  						  
						  <tr>
                            <td align="right" valign="top">2. Around Above Waist <span class="redText">*</span></td>
                            <td align="center" valign="top">:</td>
                            <td colspan="2" align="left" valign="top" class="form_small_ass">
							  <SELECT class="select_box" name="around_above_waist" id="around_above_waist" style="width:70px;" onChange="">
								  <OPTION value="" <?php if($around_above_waist==''){ ?>selected="selected" <?php } ?>>Select</OPTION>
								  	<?php
										for($i=20 ;$i<=65;$i=$i+(1/2)){
								   ?>
								   <OPTION value="<?php echo $i ?>" <?php if($around_above_waist==$i){ ?>selected="selected" <?php } ?>><?php echo $i ?></OPTION>
                               <?php } ?>
                               </SELECT>
                              &nbsp;in Inches &nbsp;
							  <img id="AAW" src="http://static.sareez.com/images/help_icon.jpg" style="cursor:pointer" alt="Help" border="0" title="Help" onclick="return hs.htmlExpand(this, { headingText: 'Around Above Waist' })" />
							  <div class="highslide-maincontent"><div class="area1">
								 <table width="580" border="0" cellspacing="0" cellpadding="0" class="popup1">
									<tr>
									  <td width="360" align="left" valign="top" class="popup1_right"><img src="http://static.sareez.com/images/utsav/around_above_waist.jpg" /></td>
									  <td width="220" align="left" valign="top" class="popup1_left">
									  <p class="heading_text"><strong>How to measure "Around Above Waist" ?</strong></p>
									  <p class="text"> For this place the tape immediately below the bust.</p></td>
									</tr>
								  </table>							  
							  </div></div>
							</td>
                          </tr>
						  						  
						  <tr>
                            <td align="right" valign="top" class="form_divider">&nbsp;</td>
                            <td align="center" valign="top" class="form_divider">&nbsp;</td>
                            <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                          </tr>
						  
						  						  
						  <tr>
                            <td align="right" valign="top">3. Shoulder <span class="redText">*</span></td>
                            <td align="center" valign="top">:</td>
                            <td colspan="2" align="left" valign="top" class="form_small_ass">
							  <SELECT class="select_box" name="shoulder" id="shoulder" style="width:70px;" onChange="">
								<OPTION value="" <?php if($shoulder==''){ ?>selected="selected" <?php } ?>>Select</OPTION>
								<?php
					 			for($i=13 ;$i<=20;$i=$i+(1/2)){
					  			?>
								<OPTION value="<?php echo $i ?>" <?php if($shoulder==$i){ ?>selected="selected" <?php } ?>><?php echo $i ?></OPTION>
								<?php } ?>
							  </SELECT>
                              &nbsp;in Inches &nbsp;
							  <img id="S" src="http://static.sareez.com/images/help_icon.jpg" style="cursor:pointer" alt="Help" border="0" title="Help" onclick="return hs.htmlExpand(this, { headingText: 'Shoulder' })" />
							  <div class="highslide-maincontent"><div class="area1"> 
								 <table width="580" border="0" cellspacing="0" cellpadding="0" class="popup1">
									<tr>
									  <td width="360" align="left" valign="top" class="popup1_right"><img src="http://static.sareez.com/images/utsav/shoulder.jpg" /></td>
									  <td width="220" align="left" valign="top" class="popup1_left">
									  <p class="heading_text"><strong>How to measure "Shoulder" ?</strong></p>
									  <p class="text">This measure has to be taken by placing the tip of the tape one any one shoulder point and stretching it straight from the back to the other shoulder point. Point means the point where you shoulder meets you arm joint.</p></td>
									</tr>
								  </table>							  
							  </div></div>
							  </td>
                          </tr>                          
						  
						  <tr>
                            <td align="right" valign="top" class="form_divider">&nbsp;</td>
                            <td align="center" valign="top" class="form_divider">&nbsp;</td>
                            <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                          </tr>
						  						  
						  						  <tr>
                            <td align="right" valign="top">4. Sleeve Length <span class="redText">*</span></td>
                            <td align="center" valign="top">:</td>
                            <td colspan="2" align="left" valign="top" class="form_small_ass">
							  <SELECT class="select_box" name="sleeve_length" id="sleeve_length" style="width:70px;" onChange="">
								<OPTION value="" <?php if($sleeve_length==''){ ?>selected="selected" <?php } ?>>Select</OPTION>
								<?php
								 for($i=0 ;$i<=23;$i=$i+(1/2)){
								  ?>
								<OPTION value="<?php echo $i ?>" <?php if($sleeve_length==$i){ ?>selected="selected" <?php } ?>><?php echo $i ?></OPTION>
								<?php } ?>
							  </SELECT>
                              &nbsp;in Inches &nbsp;
							  <img id="SL" src="http://static.sareez.com/images/help_icon.jpg" style="cursor:pointer" alt="Help" border="0" title="Help" onclick="return hs.htmlExpand(this, { headingText: 'Sleeve Length' })" />
							  <div class="highslide-maincontent"><div class="area1"><div class="area1"> 
								 <table width="580" border="0" cellspacing="0" cellpadding="0" class="popup1">
									<tr>
									  <td width="360" align="left" valign="top" class="popup1_right"><img src="http://static.sareez.com/images/utsav/sleeve_length.jpg" /></td>
									  <td width="220" align="left" valign="top" class="popup1_left">
									  <p class="heading_text"><strong>How to measure "Sleeve Length" ?</strong></p>
									  <p class="text">This is a vertical measurement. The tip of the tape on the arm joint and stretch it straight down to a desired length. Sleeves can be very short, short, medium, just above elbow, quarter length or full length.</p></td>
									</tr>
								  </table>							  
							  </div></div>
							  </td>
                          </tr>
						                            <tr>
                            <td align="right" valign="top" class="form_divider">&nbsp;</td>
                            <td align="center" valign="top" class="form_divider">&nbsp;</td>
                            <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                          </tr>
						  						  
                            <tr>
                              <td align="right" valign="top" > Sleeve Style <span class="redText">*</span></td>
                              <td align="center" valign="top">:</td>
                              <td colspan="2" align="left" valign="top" class="form_small_ass">
							  
								<input type="text" class="input_area" name="sleeve_style" id="sleeve_style" value="" readonly="readonly" />
								<a href="index.htm" onclick="return hs.htmlExpand(this, { headingText: 'Set Sleeve Style' })"> &nbsp;<img src="http://static.sareez.com/images/search_style_btn.jpg" title="Set Sleeve Style"  style="cursor:pointer; margin-top:3px;"></a>
								  <div class="highslide-maincontent">
								  <div class="area">
																		
									<div class="popup_area">
									<img src="product_thumb.php?img=images/asdescribed_sleeve.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="As Described Below">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_sleeve_style" VALUE="As Described Below" ></div> <div class="setMeas">As Described Below </div>	
									</div>									
								 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/As shown in picture_sleeve.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="As Shown in Picture">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_sleeve_style" VALUE="As Shown in Picture" ></div> <div class="setMeas">As Shown in Picture </div>	
									</div>									
								 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Asymmetrical_Sleeves.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Asymmetrical Sleeves">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_sleeve_style" VALUE="Asymmetrical Sleeves" ></div> <div class="setMeas">Asymmetrical Sleeves </div>	
									</div>									
								 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Cap_Sleeves.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Cap Sleeves">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_sleeve_style" VALUE="Cap Sleeves" ></div> <div class="setMeas">Cap Sleeves </div>	
									</div>									
								 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_7_lehenga_Back_style.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design 7">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_sleeve_style" VALUE="Design 7" ></div> <div class="setMeas">Design 7 </div>	
									</div>									
								 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Drawstring_1_Sleeves.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Drawstring 1">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_sleeve_style" VALUE="Drawstring 1" ></div> <div class="setMeas">Drawstring 1 </div>	
									</div>									
								 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Drawstring_2_Sleeves.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Drawstring 2">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_sleeve_style" VALUE="Drawstring 2" ></div> <div class="setMeas">Drawstring 2 </div>	
									</div>									
								 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Elbow_Sleeves.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Elbow">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_sleeve_style" VALUE="Elbow" ></div> <div class="setMeas">Elbow </div>	
									</div>									
								 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Flutter_Sleeves.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Flutter">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_sleeve_style" VALUE="Flutter" ></div> <div class="setMeas">Flutter </div>	
									</div>									
								 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Half_Sleeves_Sleeves.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Half Sleeve">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_sleeve_style" VALUE="Half Sleeve" ></div> <div class="setMeas">Half Sleeve </div>	
									</div>									
								 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Horse_Shoe_lehenga_Back_style.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Horse Shoe">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_sleeve_style" VALUE="Horse Shoe" ></div> <div class="setMeas">Horse Shoe </div>	
									</div>									
								 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Puff_Sleeves_Sleeves.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Puff Sleeves">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_sleeve_style" VALUE="Puff Sleeves" ></div> <div class="setMeas">Puff Sleeves </div>	
									</div>									
								 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Short_Sleeves_Sleeves.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Short Sleeves">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_sleeve_style" VALUE="Short Sleeves" ></div> <div class="setMeas">Short Sleeves </div>	
									</div>									
								 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Sleeveless_Sleeves.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Sleeveless">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_sleeve_style" VALUE="Sleeveless" ></div> <div class="setMeas">Sleeveless </div>	
									</div>									
								 									</div>
									<P>&nbsp;</P>
									<P align="center">
									 <img src="http://static.sareez.com/includes/languages/english/images/buttons/set_style.jpg" style="cursor:pointer;" onClick="set_sleeve_style();return hs.close(this)" border="0" alt="Set Style">									</P>
								  </div>							  
							  </td>
                            </tr>
							<tr>
                            <td align="right" valign="top" class="form_divider">&nbsp;</td>
                            <td align="center" valign="top" class="form_divider">&nbsp;</td>
                            <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                          </tr>
						  						
                          
						  						  <tr>
                            <td align="right" valign="top">5. Around Arm Hole <span class="redText">*</span></td>
                            <td align="center" valign="top">:</td>
                            <td colspan="2" align="left" valign="top" class="form_small_ass">
							  <SELECT class="select_box" name="arm_hole" id="arm_hole" style="width: 70px;">
								<OPTION value="" <?php if($arm_hole==''){ ?>selected="selected" <?php } ?>>Select</OPTION>
								<?php
								 for($i=5 ;$i<=25;$i=$i+(1/2)){
								  ?>
								<OPTION value="<?php echo $i ?>" <?php if($arm_hole==$i){ ?>selected="selected" <?php } ?>><?php echo $i ?></OPTION>
								<?php } ?>
							  </SELECT>
                              &nbsp;in Inches &nbsp;
							  <img id="AAH" src="http://static.sareez.com/images/help_icon.jpg" style="cursor:pointer" alt="Help" border="0" title="Help" onclick="return hs.htmlExpand(this, { headingText: 'Around Arm Hole' })" />
							  <div class="highslide-maincontent"><div class="area1"> 
								 <table width="580" border="0" cellspacing="0" cellpadding="0" class="popup1">
									<tr>
									  <td width="360" align="left" valign="top" class="popup1_right"><img src="http://static.sareez.com/images/utsav/around_arm_hole.jpg" /></td>
									  <td width="220" align="left" valign="top" class="popup1_left">
									  <p class="heading_text"><strong>How to measure "Around Arm Hole" ?</strong></p>
									  <p class="text">For this measurement, keep you arms hanging and relaxed. Place the tip of the tape on the shoulder point as you did for the sleeves. But this time drop it to the back, bring it below the under arm and at the shoulder point to complete the circle.</p></td>
									</tr>
								  </table>							  
							  </div></div>
							  </td>
                          </tr>
						  	
                          <tr>
                            <td align="right" valign="top" class="form_divider">&nbsp;</td>
                            <td align="center" valign="top" class="form_divider">&nbsp;</td>
                            <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                          </tr>
						  
						  						  <tr>
                            <td align="right" valign="top">6. Around Arm <span class="redText">*</span></td>
                            <td align="center" valign="top">:</td>
                            <td colspan="2" align="left" valign="top" class="form_small_ass">
							  <SELECT class="select_box" name="around_arm" id="around_arm" style="width: 70px;">
								<OPTION value="" <?php if($around_arm==''){ ?>selected="selected" <?php } ?>>Select</OPTION>
								<?php
								 for($i=5 ;$i<=25;$i=$i+(1/2)){
								 ?>
								<OPTION value="<?php echo $i ?>" <?php if($around_arm==$i){ ?>selected="selected" <?php } ?>><?php echo $i ?></OPTION>
								<?php } ?>
							  </SELECT>
                              &nbsp;in Inches &nbsp;
							  <img id="AA" src="http://static.sareez.com/images/help_icon.jpg" style="cursor:pointer" alt="Help" border="0" title="Help" onclick="return hs.htmlExpand(this, { headingText: 'Around Arm' })" />
							  <div class="highslide-maincontent"><div class="area1"> 
								 <table width="580" border="0" cellspacing="0" cellpadding="0" class="popup1">
									<tr>
									  <td width="360" align="left" valign="top" class="popup1_right"><img src="http://static.sareez.com/images/utsav/around_arm.jpg" /></td>
									  <td width="220" align="left" valign="top" class="popup1_left">
									  <p class="heading_text"><strong>How to measure "Around Arm" ?</strong></p>
									  <p class="text">For this keep your arms relaxed. Place the tape on the middle of your biceps, take it round your relaxed arm and complete the circle.</p></td>
									</tr>
								  </table>							  
							  </div></div>
							  </td>
                          </tr>
						  						  
                          <tr>
                            <td align="right" valign="top" class="form_divider">&nbsp;</td>
                            <td align="center" valign="top" class="form_divider">&nbsp;</td>
                            <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                          </tr>
						  
						  						  <tr>
                            <td align="right" valign="top">7. Front Neck Depth <span class="redText">*</span></td>
                            <td align="center" valign="top">:</td>
                            <td colspan="2" align="left" valign="top" class="form_small_ass">
							  <SELECT class="select_box" name="front_neck_depth" id="front_neck_depth" style="width: 70px;">
								<OPTION value="" <?php if($front_neck_depth==''){ ?>selected="selected" <?php } ?>>Select</OPTION>
								<?php
								 for($i=1 ;$i<=8;$i=$i+(1/2)){
								 ?>
								<OPTION value="<?php echo $i ?>" <?php if($front_neck_depth==$i){ ?>selected="selected" <?php } ?>><?php echo $i ?></OPTION>
								<?php } ?>
								</SELECT>
                              &nbsp;in Inches &nbsp;
							  <img id="FND" src="http://static.sareez.com/images/help_icon.jpg" style="cursor:pointer" alt="Help" border="0" title="Help" onclick="return hs.htmlExpand(this, { headingText: 'Front Neck Depth' })" />
							  <div class="highslide-maincontent"><div class="area1"> 
								 <table width="580" border="0" cellspacing="0" cellpadding="0" class="popup1">
									<tr>
									  <td width="360" align="left" valign="top" class="popup1_right"><img src="http://static.sareez.com/images/utsav/front_neck_depth.jpg" /></td>
									  <td width="220" align="left" valign="top" class="popup1_left">
									  <p class="heading_text"><strong>How to measure "Front Neck Depth" ?</strong></p>
									  <p class="text"> For this place the tip of the tape on the any one side of your neck and stretch it diagonally to the centre just above you bust to your desired depth.</p></td>
									</tr>
								  </table>							  
							  </div></div>
							  </td>
                          </tr>
						  						  
						  
                          <tr>
                            <td align="right" valign="top" class="form_divider">&nbsp;</td>
                            <td align="center" valign="top" class="form_divider">&nbsp;</td>
                            <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                          </tr>
						  
						                                <tr>
                              <td align="right" valign="top" > Front Neck Style <span class="redText">*</span></td>
                              <td align="center" valign="top">:</td>
                              <td colspan="2" align="left" valign="top" class="form_small_ass">
								<input type="text" class="input_area" name="front_neck_style" id="front_neck_style" value="" readonly="readonly" />
								<a href="index.htm" onclick="return hs.htmlExpand(this, { headingText: 'Set Front neck style' })">
								<img src="http://static.sareez.com/images/search_style_btn.jpg" title="Set Front Neck Style" style="cursor:pointer" />
								</a>
								  <div class="highslide-maincontent">
								  <div class="area">
																		
									<div class="popup_area">
									<img src="product_thumb.php?img=images/asdescribed.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="As Described Below">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="As Described Below" ></div> <div class="setMeas">As Described Below</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/As shown in picture.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="As Shown in Picture">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="As Shown in Picture" ></div> <div class="setMeas">As Shown in Picture</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Bustier.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Bustier">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Bustier" ></div> <div class="setMeas">Bustier</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Chinese_Collar.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Chinese Collar">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Chinese Collar" ></div> <div class="setMeas">Chinese Collar</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/decollete.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Decollete">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Decollete" ></div> <div class="setMeas">Decollete</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/design_1.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 1">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 1" ></div> <div class="setMeas">Design No. 1</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/design_10.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 10">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 10" ></div> <div class="setMeas">Design No. 10</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_11_front.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 11">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 11" ></div> <div class="setMeas">Design No. 11</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_12_front.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 12">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 12" ></div> <div class="setMeas">Design No. 12</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_13.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 13">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 13" ></div> <div class="setMeas">Design No. 13</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_14.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 14">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 14" ></div> <div class="setMeas">Design No. 14</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_15.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 15">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 15" ></div> <div class="setMeas">Design No. 15</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_16.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 16">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 16" ></div> <div class="setMeas">Design No. 16</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_17.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 17">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 17" ></div> <div class="setMeas">Design No. 17</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/design_2.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 2">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 2" ></div> <div class="setMeas">Design No. 2</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_3.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 3">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 3" ></div> <div class="setMeas">Design No. 3</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_4.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 4">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 4" ></div> <div class="setMeas">Design No. 4</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_5.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 5">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 5" ></div> <div class="setMeas">Design No. 5</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_6_front.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 6">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 6" ></div> <div class="setMeas">Design No. 6</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_7_front.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 7">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 7" ></div> <div class="setMeas">Design No. 7</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_8_front.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 8">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 8" ></div> <div class="setMeas">Design No. 8</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/design_9.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 9">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Design No. 9" ></div> <div class="setMeas">Design No. 9</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Envelope.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Envelope">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Envelope" ></div> <div class="setMeas">Envelope</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/halter_neck.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Halter Neck">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Halter Neck" ></div> <div class="setMeas">Halter Neck</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/halter_neck_2.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Halter Neck 2">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Halter Neck 2" ></div> <div class="setMeas">Halter Neck 2</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/haltaer_neck_3.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Halter Neck 3">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Halter Neck 3" ></div> <div class="setMeas">Halter Neck 3</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Horse_Shoe.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Horse Shoe">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Horse Shoe" ></div> <div class="setMeas">Horse Shoe</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Off_shoulder_front.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Off Shoulder">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Off Shoulder" ></div> <div class="setMeas">Off Shoulder</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/one_shoulsder.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="One Shoulder">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="One Shoulder" ></div> <div class="setMeas">One Shoulder</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Pointed_u_neck.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Pointed U Neck">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Pointed U Neck" ></div> <div class="setMeas">Pointed U Neck</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/rounded_sweetheart .jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Rounded Sweet Heart">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Rounded Sweet Heart" ></div> <div class="setMeas">Rounded Sweet Heart</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Scalloped.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Scalloped">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Scalloped" ></div> <div class="setMeas">Scalloped</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Square.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Square">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Square" ></div> <div class="setMeas">Square</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/string_style.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="String Style">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="String Style" ></div> <div class="setMeas">String Style</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Sweet_hear.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Sweet Heart">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Sweet Heart" ></div> <div class="setMeas">Sweet Heart</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Sweet_heart_with_Collor.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Sweet Heart with Collar">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="Sweet Heart with Collar" ></div> <div class="setMeas">Sweet Heart with Collar</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/u_neck.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="U Neck">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="U Neck" ></div> <div class="setMeas">U Neck</div>	
									</div>									
									 									
									<div class="popup_area">
									<img src="product_thumb.php?img=images/V_neck.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="V Neck">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_front_neck_style" VALUE="V Neck" ></div> <div class="setMeas">V Neck</div>	
									</div>									
									 									</div>
									<P>&nbsp;</P>
									<P align="center">
									<img src="http://static.sareez.com/includes/languages/english/images/buttons/set_style.jpg" style="cursor:pointer;" onClick="set_front_neck_style();return hs.close(this)" border="0" alt="Set Style">									</P>
								  </div>
							  </td>
                            </tr>
							<tr>
                              <td align="right" valign="top" class="form_divider">&nbsp;</td>
                              <td align="center" valign="top" class="form_divider">&nbsp;</td>
                              <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                            </tr>
                            							
						
						  	
						  <tr>
                            <td align="right" valign="top">8. Back Neck Depth <span class="redText">*</span></td>
                            <td align="center" valign="top">:</td>
                            <td colspan="2" align="left" valign="top" class="form_small_ass">
							  <SELECT class="select_box" name="back_neck_depth" id="back_neck_depth" style="width: 70px;">
								<OPTION value="" <?php if($back_neck_depth==''){ ?>selected="selected" <?php } ?>>Select</OPTION>
								<?php
								 for($i=1 ;$i<=10;$i=$i+(1/2)){
								  ?>
								<OPTION value="<?php echo $i ?>" <?php if($back_neck_depth==$i){ ?>selected="selected" <?php } ?>><?php echo $i ?></OPTION>
								<?php } ?>
							  </SELECT>
                              &nbsp;in Inches &nbsp;
							  <img id="BND" src="http://static.sareez.com/images/help_icon.jpg" style="cursor:pointer" alt="Help" border="0" title="Help" onclick="return hs.htmlExpand(this, { headingText: 'Back Neck Depth' })" />
							  <div class="highslide-maincontent"><div class="area1"> 
								 <table width="580" border="0" cellspacing="0" cellpadding="0" class="popup1">
									<tr>
									  <td width="360" align="left" valign="top" class="popup1_right"><img src="http://static.sareez.com/images/utsav/Back_neck_depth.jpg" /></td>
									  <td width="220" align="left" valign="top" class="popup1_left">
									  <p class="heading_text"><strong>How to measure "Back Neck Depth" ?</strong></p>
									  <p class="text"> Similar to the Front Neck Depth. Place the tip of the tape on the side of you neck and stretch it back to a desired point on the spine.</p></td>
									</tr>
								  </table>							  
							  </div></div>
							  </td>
                          </tr>
                          					  
						  
						  						  <tr>
                            <td align="right" valign="top" class="form_divider">&nbsp;</td>
                            <td align="center" valign="top" class="form_divider">&nbsp;</td>
                            <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                          </tr>
                          <tr>
                              <td align="right" valign="top" > Back Neck Style <span class="redText">*</span></td>
                              <td align="center" valign="top">:</td>
                              <td colspan="2" align="left" valign="top" class="form_small_ass">
								<input type="text" class="input_area" name="back_neck_style" id="back_neck_style" value=""  readonly="readonly"/>
								<a href="index.htm" onclick="return hs.htmlExpand(this, { headingText: 'Set Back neck style' })">
								<img src="http://static.sareez.com/images/search_style_btn.jpg" title="Set Back Neck Style" style="cursor:pointer" />
								</a>
								  <div class="highslide-maincontent">
								  <div class="area">
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/asdescribed.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="As Described Below">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="As Described Below" ></div> <div class="setMeas">As Described Below</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/As_shown_in_picture.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="As Shown in Picture">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="As Shown in Picture" ></div> <div class="setMeas">As Shown in Picture</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Asymmetrical.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Asymmetrical">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Asymmetrical" ></div> <div class="setMeas">Asymmetrical</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Back_bustier .jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Back Bustier">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Back Bustier" ></div> <div class="setMeas">Back Bustier</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Back_butterfly_bustier.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Back Butterfly Bustier">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Back Butterfly Bustier" ></div> <div class="setMeas">Back Butterfly Bustier</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Back_chinese_collar.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Back Chinese Collar">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Back Chinese Collar" ></div> <div class="setMeas">Back Chinese Collar</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Bateu_or_boat .jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Bateu or Boat">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Bateu or Boat" ></div> <div class="setMeas">Bateu or Boat</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_1.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 1">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Design No. 1" ></div> <div class="setMeas">Design No. 1</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_10.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 10">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Design No. 10" ></div> <div class="setMeas">Design No. 10</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_11.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 11">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Design No. 11" ></div> <div class="setMeas">Design No. 11</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_12.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 12">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Design No. 12" ></div> <div class="setMeas">Design No. 12</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_2.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 2">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Design No. 2" ></div> <div class="setMeas">Design No. 2</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_3.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 3">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Design No. 3" ></div> <div class="setMeas">Design No. 3</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_4.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 4">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Design No. 4" ></div> <div class="setMeas">Design No. 4</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_5.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 5">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Design No. 5" ></div> <div class="setMeas">Design No. 5</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_6.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 6">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Design No. 6" ></div> <div class="setMeas">Design No. 6</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_7.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 7">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Design No. 7" ></div> <div class="setMeas">Design No. 7</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_8.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 8">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Design No. 8" ></div> <div class="setMeas">Design No. 8</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Design_9.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Design No. 9">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Design No. 9" ></div> <div class="setMeas">Design No. 9</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Horse_Shoe.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Horse Shoe">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Horse Shoe" ></div> <div class="setMeas">Horse Shoe</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Off_shoulder.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Off Shoulder">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Off Shoulder" ></div> <div class="setMeas">Off Shoulder</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/One_shoulder_back.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="One Shoulder Back">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="One Shoulder Back" ></div> <div class="setMeas">One Shoulder Back</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Pointed.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Pointed Back">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Pointed Back" ></div> <div class="setMeas">Pointed Back</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/Square_with_laces.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="Square with Laces">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="Square with Laces" ></div> <div class="setMeas">Square with Laces</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/String_Style_1.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="String Style 1">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="String Style 1" ></div> <div class="setMeas">String Style 1</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/String_Style_2.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="String Style 2">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="String Style 2" ></div> <div class="setMeas">String Style 2</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/String_Style_3 .jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="String Style 3">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="String Style 3" ></div> <div class="setMeas">String Style 3</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/String_Style_4.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="String Style 4">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="String Style 4" ></div> <div class="setMeas">String Style 4</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/U_neck.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="U Neck Back">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="U Neck Back" ></div> <div class="setMeas">U Neck Back</div>	
									</div>	
																		 
									<div class="popup_area">
									<img src="product_thumb.php?img=images/V_neck.jpg&w=107&h=107" width="107" height="107" hspace="5" border="0" alt="V Neck Back">									<br />
									
									<div class="setMeasRbox"><INPUT TYPE="radio" NAME="rdo_back_neck_style" VALUE="V Neck Back" ></div> <div class="setMeas">V Neck Back</div>	
									</div>	
																	
									 </div>
									<P>&nbsp;</P>
									<P align="center">
									  <img src="http://static.sareez.com/includes/languages/english/images/buttons/set_style.jpg" style="cursor:pointer;" onClick="set_back_neck_style();return hs.close(this)" border="0" alt="Set Style">									</P>
								  </div>
							  </td>
                            </tr>
                          						  
						  						 
						  
						  						  
						  
						  						  
						  
						  					  
						  
						  						  
						  <!-- <tr>
                              <td align="right" valign="top" class="form_divider">&nbsp;</td>
                              <td align="center" valign="top" class="form_divider">&nbsp;</td>
                              <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                            </tr>
						  <tr>
                            <td align="right" valign="top">9. Closing Side <span class="redText">*</span></td>
                            <td align="center" valign="top">:</td>
                            <td colspan="2" align="left" valign="top" class="form_small_ass">
							<SELECT class="select_box" name="closing_side" id="closing_side" onChange="">
								<OPTION value="" selected="selected" >Select</OPTION>
								<OPTION value="As Shown"  >As Shown</OPTION>
								<OPTION value="Back" >Back</OPTION>
								<OPTION value="Front" >Front</OPTION>
								<OPTION value="As Described Below" >As Described Below</OPTION>
							  </SELECT>
							  </td>
                          </tr>
                          <tr>
                            <td align="right" valign="top" class="form_divider">&nbsp;</td>
                            <td align="center" valign="top" class="form_divider">&nbsp;</td>
                            <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                          </tr>
						  <tr>
                            <td align="right" valign="top">10. Closing with <span class="redText">*</span></td>
                            <td align="center" valign="top">:</td>
                            <td colspan="2" align="left" valign="top" class="form_small_ass">
							<SELECT class="select_box" name="closing_with" id="closing_with" onChange="">
								<OPTION value="NA"  selected="selected" >Select</OPTION>
								<OPTION value="As Shown"   >As Shown</OPTION>
								<OPTION value="Hook"  >Hook</OPTION>
								<OPTION value="Zip"   >Zip</OPTION>
								<OPTION value="As Described Below"   >As Described Below</OPTION>
							</SELECT>
							</td>
                          </tr>-->
						  						                            <tr>
                            <td align="right" valign="top" class="form_divider">&nbsp;</td>
                            <td align="center" valign="top" class="form_divider">&nbsp;</td>
                            <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                          </tr>
                        </table></td>
                      </tr>
                    </table>
					<table width="706" border="0" cellpadding="0" cellspacing="0" class="address_book_text">
                     					  <tr>
                        <td width="175" align="left" valign="middle" class="form_area_heading"><img src="http://static.sareez.com/images/form_arrow.jpg" />&nbsp;&nbsp;<strong>For Saree Only</strong></td>
                        <td width="531" colspan="2" align="right" valign="middle" class="form_area_heading1">[ <span class="redText">*</span> marked fields are mandatory ]</td>
                      </tr>
					                       					  
					 					  
                                           <tr>
                        <td colspan="3" align="left" valign="top"><table width="700" border="0" cellspacing="0" cellpadding="0">
                     		<tr>
                              <td width="175">&nbsp;</td>
                              <td width="531">&nbsp;</td>
                              <td width="320">&nbsp;</td>
                              <td width="5">&nbsp;</td>
                            </tr> 
                                                 <tr>
                              <td height="22" align="right" valign="top"><strong>Blouse (Top)</strong></td>
                              <td align="center" valign="top">&nbsp;</td>
                              <td colspan="2" align="left" valign="top" class="form_small_ass">&nbsp;</td>
                              <td width="188" rowspan="22" align="center" valign="top"></td>
                            </tr>
                            <tr>
                              <td align="right" valign="top" class="form_divider">&nbsp;</td>
                              <td align="center" valign="top" class="form_divider">&nbsp;</td>
                              <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                            </tr>
                          <tr>
                              <td align="right" valign="top">1. Blouse Length <span class="redText">*</span></td>
                              <td align="center" valign="top">:</td>
                              <td colspan="2" align="left" valign="top" class="form_small_ass">
								<SELECT class="select_box" name="blouse_length" id="blouse_length" style="width: 70px;">
									<OPTION value="" <?php if($blouse_length==''){ ?>selected="selected" <?php } ?>>Select</OPTION>
                                    <?php
									 for($i=12 ;$i<=20;$i=$i+(1/2)){
									  ?>
									<OPTION value="<?php echo $i ?>" <?php if($blouse_length==$i){ ?>selected="selected" <?php } ?>><?php echo $i ?></OPTION>
									<?php } ?>
                                </SELECT>&nbsp;in Inches &nbsp;	
							  <img id="BL" src="http://static.sareez.com/images/help_icon.jpg" style="cursor:pointer" alt="Help" border="0" title="Help" onclick="return hs.htmlExpand(this, { headingText: 'Blouse Length' })" />
							  <div class="highslide-maincontent"><div class="area1"> 
								 <table width="580" border="0" cellspacing="0" cellpadding="0" class="popup1">
									<tr>
									  <td width="360" align="left" valign="top" class="popup1_right"><img src="http://static.sareez.com/images/utsav/blouse_length.jpg" /></td>
									  <td width="220" align="left" valign="top" class="popup1_left">
									  <p class="heading_text"><strong>How to measure "Blouse Length" ?</strong></p>
									  <p class="text"> Place the tip of the tape on any side of your neck and bring it down the back to a desired length just below the bust.</p></td>
									</tr>
								  </table>	
							  </div>								</td>
                            </tr>
                            <tr>
                              <td align="right" valign="top" class="form_divider">&nbsp;</td>
                              <td align="center" valign="top" class="form_divider">&nbsp;</td>
                              <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                            </tr>
							                                                 <tr>
                              <td height="22" align="right" valign="top"><strong>Petticoat (Bottom Skirt)</strong></td>
                              <td align="center" valign="top">&nbsp;</td>
                              <td colspan="2" align="left" valign="top" class="form_small_ass">&nbsp;</td>
                            </tr>
                            <tr>
                              <td align="right" valign="top" class="form_divider">&nbsp;</td>
                              <td align="center" valign="top" class="form_divider">&nbsp;</td>
                              <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                            </tr>
                            <tr>
                              <td align="right" valign="top">1. Petticoat Length <span class="redText">*</span></td>
                              <td align="center" valign="top">&nbsp;</td>
                              <td colspan="2" align="left" valign="top" class="form_small_ass">
							  <SELECT class="select_box" name="petticoat_length" id="petticoat_length" style="width: 70px;" >
								<OPTION value="" <?php if($petticoat_length==''){ ?>selected="selected" <?php } ?>>Select</OPTION>
								<?php
								 for($i=30 ;$i<=45;$i=$i+(1/2)){
								  ?>
								<OPTION value="<?php echo $i ?>" <?php if($petticoat_length==$i){ ?>selected="selected" <?php } ?>><?php echo $i ?></OPTION>
								<?php } ?>
								</SELECT>&nbsp;in Inches &nbsp;
							  
							  <img id="PL" src="http://static.sareez.com/images/help_icon.jpg" style="cursor:pointer" alt="Help" border="0" title="Help" onclick="return hs.htmlExpand(this, { headingText: 'Petticoat Length' })" />
							  <div class="highslide-maincontent"><div class="area1"> 
								 <table width="580" border="0" cellspacing="0" cellpadding="0" class="popup1">
									<tr>
									  <td width="360" align="left" valign="top" class="popup1_right"><img src="http://static.sareez.com/images/utsav/petticoat_length.jpg" /></td>
									  <td width="220" align="left" valign="top" class="popup1_left">
									  <p class="heading_text"><strong>How to measure "Petticoat Length" ?</strong></p>
									  <p class="text"> Place the tip of the tape on any side of your waist or hipbone, depending on where you wear you lehnga or saree. Then let it fall down straight. Hold it slightly above your ankles.</p></td>
									</tr>
								  </table>	
							  </div>							  </td>
                            </tr>
                            <tr>
                              <td align="right" valign="top" class="form_divider">&nbsp;</td>
                              <td align="center" valign="top" class="form_divider">&nbsp;</td>
                              <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                            </tr>
							                     							
					 		
							
                     							<tr>
                              <td align="right" valign="top">Instruction (if any)<br />Maximum 500 characters<span class="redText">&nbsp;</span></td>
                              <td align="center" valign="top">:</td>
                              <td colspan="2" align="left" valign="top" class="form_small_ass">
<textarea id="instructions" name="instructions" class="carttext" cols="45" rows="3" onFocus="textCounter(document.measure.instructions,document.measure.remLen,500)" onKeyDown="textCounter(document.measure.instructions,document.measure.remLen,500)" onClick="textCounter(document.measure.instructions,document.measure.remLen,500)"></textarea>
							  <BR>
							  <SPAN class="carttext">You have
							  <INPUT readonly="" name="remLen" type="text" class="input_area" value="500" style="border-width:0;text-align:center;width:40px">
							  characters left.</SPAN>							  
							  
							  <div class="highslide-maincontent"> 
							  <P>
							  <img src="http://static.sareez.com/images/utsav/sleeve_length.jpg" />							  </P>
							  <p>
							  Starting from the outside edge of shoulder bone and measure upto the desired length.							  </p>
							  </div>							  </td>
                            </tr>
							<tr>
                              <td align="right" valign="top" class="form_divider">&nbsp;</td>
                              <td align="center" valign="top" class="form_divider">&nbsp;</td>
                              <td colspan="2" align="left" valign="top" class="form_divider">&nbsp;</td>
                            </tr>
                        </table></td>
                      </tr>
                    </table>
					<table cellpadding="0" cellspacing="0" class="address_book_btn">
						<tr>
							<td colspan="2" class="accOdrNumber">						  </td>
							<td width="396" class="accOdrStat">
							<input type="image" src="http://static.sareez.com/includes/languages/english/images/buttons/button_confirm.gif" border="0" alt="Confirm" title=" Confirm ">							&nbsp;<img src="images/reset.jpg" onClick="document.measure.reset()" border="0" style="cursor:pointer;" /></td>
						</tr>
					</table>
					<table cellpadding="0" cellspacing="0" style="margin:10px 0 0 0;">
						<tr>
							<td colspan="2"><a href="#"></a></td>
						</tr>
												<tr>
							<td colspan="2"><img src="images/pixel_trans.gif" width="1" height="10" border="0" alt=""></td>
						</tr>
					  <tr>
				<td bgcolor="#FFFFFF" background="http://static.sareez.com/images/measurement_footer.jpg" height="205px" width="756px"  colspan="2">
				  <p></p></td>
					  </tr>
					</table>
					
			  </td>
			</tr>
		</table>
		</form>
