<script type="text/javascript" src="<?php echo $this->getSkinUrl() ?>highslide/wz_tooltip.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl() ?>highslide/tip_balloon.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl() ?>highslide/highslide_area1.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl() ?>highslide/highslide.css" />
<script type="text/javascript" src="<?php echo $this->getSkinUrl() ?>highslide/highslide-with-html.js"></script>
<script>
    hs.graphicsDir = '<?php echo $this->getSkinUrl() ?>highslide/graphics/';
    hs.outlineType = 'rounded-white';
    hs.showCredits = false;
    hs.wrapperClassName = 'draggable-header';
    hs.allowWidthReduction = true;
    hs.allowHeightReduction = true;
</script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl() ?>highslide/highslide-fun.js"></script>
<style>
    .highslide-maincontent {
        display: none;
    }
</style> 
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl() . 'css/popup.css' ?>">
<?php

if(Mage::getSingleton('customer/session')->isLoggedIn())
 {
	 $customerId = Mage::getModel('customer/session')->getCustomer()->getId();
 }
 
 
$measurement_id	= $this->getRequest()->getParam('m_id');
/*$mforusermodel = Mage::getModel('measurement/measurementforuser')->getCollection()
->AddFieldToFilter('user_id' , $customerId)
->AddFieldToFilter('measurement_id' , $measurement_id )
->getData();
*/


?>
              <div class="page-title">
                <h1>Measurement History</h1>
              </div>
<?php
$mformeasurmentmodel = Mage::getModel('measurement/measurement')->getCollection()
->AddFieldToFilter('measurement_id' ,$measurement_id)
->getData();


if(count($mformeasurmentmodel)>0)
{
 $measurement_type = $mformeasurmentmodel[0]['measurement_type'];

if($measurement_type == 'blouse')
{

?>
<div class="page-title">
    <h3>Blouse ReadyMade Size</h3>
</div>
              <table class="table table-hover table-border" width="700" border="0" cellspacing="0" cellpadding="0">
						<tbody>
                        <tr>
                        <td valign="middle" align="center" class="textaligncenter" colspan="3"><strong><span class="redText"></span> (<?php echo $mformeasurmentmodel[0]['body_garment']; ?>)</strong></td>
                      </tr>
                        <tr>
						  <td colspan="3" align="left" valign="middle" class="form_area_heading">&nbsp;&nbsp;<strong>General Measurement <!--BL-->:</strong></td>
						  
						  </tr>
                          
						  <tr>
                            <td width="174" align="left" valign="top">1. Around Bust</td>
                            <td width="12" align="center" valign="middle"><strong>:</strong></td>
                            <td width="512" align="left" valign="top" class="ass_text">
							<?php echo $mformeasurmentmodel[0]['around_bust']; ?>							</td>
                          </tr>
                          <tr>
                            <td valign="top" align="left">2. Around Above Waist</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							<?php echo $mformeasurmentmodel[0]['around_above_waist']; ?>								</td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">3. Shoulder</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							 <?php echo $mformeasurmentmodel[0]['shoulder']; ?>								  </td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">4. Sleeve Length</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['sleeve_length']; ?>							  </td>
                          </tr>
                          	
													    <tr>
                              <td valign="top" align="left"> Sleeve Style </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['sleeve_style']; ?>							  </td>
                            </tr>
						  						  
						  <tr>
                            <td valign="top" align="left">5. Around Arm Hole</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['around_arm_hole']; ?>							  </td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">6. Around Arm</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							 <?php echo $mformeasurmentmodel[0]['around_arm']; ?>							  </td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">7. Front Neck Depth </td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							 <?php echo $mformeasurmentmodel[0]['front_neck_depth']; ?>							  </td>
                          </tr>
						  
						                              <tr>
                              <td valign="top" align="left"> Front Neck Style </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['front_neck_style']; ?>								  </td>
                            </tr>
						  						  
						  <tr>
                            <td valign="top" align="left">8. Back Neck Depth</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['back_neck_depth']; ?>							  </td>
                          </tr>
                            
														<tr>
                              <td valign="top" align="left"> Back Neck Style </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['back_neck_style']; ?>							  </td>
                            </tr>
                                                 <tr>
							  <td colspan="3" align="left" valign="middle" class="form_area_heading">&nbsp;&nbsp;<strong>Blouse (Top):</strong></td>
						    </tr>
                          <tr>
                              <td valign="top" align="left">1. Blouse Length </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['blouse_length']; ?>									</td>
                            </tr>
							                                                 <tr>
							  <td colspan="3" align="left" valign="middle" class="form_area_heading">&nbsp;&nbsp;<strong>Petticoat (Bottom Skirt)</strong></td>
						    </tr>
                            <tr>
                              <td valign="top" align="left">1. Petticoat Length </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['petticoat_length']; ?>	 							  </td>
                            </tr>
							                                          							<tr>
                              <td valign="top" align="left">Instruction </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
								<?php echo $mformeasurmentmodel[0]['instructions']; ?>							  </td>
                            </tr>
                        </tbody></table>

<?php }elseif($measurement_type == 'lehenga'){?>
<div class="page-title">
    <h3>Lahenga ReadyMade Size</h3>
</div>
      <table class="table table-hover table-border" width="700" border="0" cellspacing="0" cellpadding="0">
						<tbody>
                        <tr>
                        <td valign="middle" align="center" class="textaligncenter" colspan="3"><strong><span class="redText"></span> (<?php echo $mformeasurmentmodel[0]['body_garment']; ?>)</strong></td>
                      </tr>
                        <tr>
						  <td colspan="3" align="left" valign="middle" class="form_area_heading">&nbsp;&nbsp;<strong>General Measurement <!--LL-->:</strong></td>
						  
						  </tr>
						  <tr>
                            <td width="176" align="left" valign="top">1. Around Bust</td>
                            <td width="10" align="center" valign="middle"><strong>:</strong></td>
                            <td width="520" align="left" valign="top" class="ass_text">
							<?php echo $mformeasurmentmodel[0]['around_bust']; ?>							</td>
                          </tr>
                          <tr>
                            <td valign="top" align="left">2. Around Above Waist</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							<?php echo $mformeasurmentmodel[0]['around_above_waist']; ?>								</td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">3. Shoulder</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							 <?php echo $mformeasurmentmodel[0]['shoulder']; ?>								  </td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">4. Sleeve Length</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['sleeve_length']; ?>							  </td>
                          </tr>
                          	
													    <tr>
                              <td valign="top" align="left"> Sleeve Style </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['sleeve_style']; ?>							  </td>
                            </tr>
						  						  
						  <tr>
                            <td valign="top" align="left">5. Around Arm Hole</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['around_arm_hole']; ?>							  </td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">6. Around Arm</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							 <?php echo $mformeasurmentmodel[0]['around_arm']; ?>							  </td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">7. Front Neck Depth </td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							 <?php echo $mformeasurmentmodel[0]['front_neck_depth']; ?>							  </td>
                          </tr>
						  
						                              <tr>
                              <td valign="top" align="left"> Front Neck Style </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['front_neck_style']; ?>								  </td>
                            </tr>
						  						  
						  <tr>
                            <td valign="top" align="left">8. Back Neck Depth</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['back_neck_depth']; ?>							  </td>
                          </tr>
                            
														<tr>
                              <td valign="top" align="left"> Back Neck Style </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['back_neck_style']; ?>							  </td>
                            </tr>
						  <tr>
                            <td valign="top" align="left">11. Lining</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							  <?php if($mformeasurmentmodel[0]['lining']==1){ echo 'Yes'; }else{ echo 'No'; } ?>							  </td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">12.Around Waist</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['around_waist']; ?>							  </td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">13.Around Hips</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['around_hips']; ?>							  </td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">14.Your Height</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['your_height']; ?>							  </td>
                          </tr>
                                                 
                          <tr>
							  <td colspan="3" align="left" valign="middle" class="form_area_heading">&nbsp;&nbsp;<strong>Lehenga Top:</strong></td>
						    </tr>
                          <tr>
                              <td valign="top" align="left">1. Choli Length </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['choli_length']; ?>									</td>
                            </tr>
							                                                 <tr>
							  <td colspan="3" align="left" valign="middle" class="form_area_heading">&nbsp;&nbsp;<strong><!--Petticoat (Bottom Skirt)-->Lehenga Bottom:</strong></td>
						    </tr>
                            <tr>
                              <td valign="top" align="left">1. Lehenga Style</td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['lehnga_style']; ?>	 							  </td>
                            </tr>
                            <tr>
                              <td valign="top" align="left">2. Lehenga Length </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['lehenga_length']; ?>	 							  </td>
                            </tr>
                            <tr>
                              <td valign="top" align="left">3. Back Elastic </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php //echo $mformeasurmentmodel[0]['elastic']; ?><?php if($mformeasurmentmodel[0]['elastic']=='yes'){ echo 'Yes'; }else{ echo 'No'; } ?></td>
                            </tr>
							                                          							<tr>
                              <td valign="top" align="left">Instruction </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
								<?php echo $mformeasurmentmodel[0]['instructions']; ?>							  </td>
                            </tr>
							<tr>
                              <td valign="top" align="right" class="form_divider">&nbsp;</td>
                              <td valign="middle" align="center" class="form_divider">&nbsp;</td>
                              <td valign="top" align="left" class="form_divider">&nbsp;</td>
                            </tr>
                            
                        </tbody></table> 
<?php }else{?>
<div class="page-title">
    <h3>ReadyMade Size</h3>
</div>
      <table class="table table-hover table-border" width="700" border="0" cellspacing="0" cellpadding="0">
						<tbody>
                        <tr>
                        <td valign="middle" align="center" colspan="3" class="textaligncenter"><strong><span class="redText"></span> (<?php echo $mformeasurmentmodel[0]['body_garment']; ?> )</strong></td>
                      </tr>
                        <tr>
						  <td colspan="3" align="left" valign="middle" class="form_area_heading">&nbsp;&nbsp;<strong>General Measurement <!--SL-->:</strong></td>
						  
						  </tr>
						  <tr>
                            <td width="170" align="left" valign="top">1. Around Bust</td>
                            <td width="10" align="center" valign="middle"><strong>:</strong></td>
                            <td width="520" align="left" valign="top" class="ass_text">
							<?php echo $mformeasurmentmodel[0]['around_bust']; ?>							</td>
                          </tr>
                          <tr>
                            <td valign="top" align="left">2. Around Above Waist</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							<?php echo $mformeasurmentmodel[0]['around_above_waist']; ?>								</td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">3. Shoulder</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							 <?php echo $mformeasurmentmodel[0]['shoulder']; ?>								  </td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">4. Sleeve Length</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['sleeve_length']; ?>							  </td>
                          </tr>
                          	
													    <tr>
                              <td valign="top" align="left"> Sleeve Style </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['sleeve_style']; ?>							  </td>
                            </tr>
						  						  
						  <tr>
                            <td valign="top" align="left">5. Around Arm Hole</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['around_arm_hole']; ?>							  </td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">6. Around Arm</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							 <?php echo $mformeasurmentmodel[0]['around_arm']; ?>							  </td>
                          </tr>
						  <tr>
                            <td valign="top" align="left">7. Front Neck Depth </td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							 <?php echo $mformeasurmentmodel[0]['front_neck_depth']; ?>							  </td>
                          </tr>
						  
						                              <tr>
                              <td valign="top" align="left"> Front Neck Style </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['front_neck_style']; ?>								  </td>
                            </tr>
						  						  
						  <tr>
                            <td valign="top" align="left">8. Back Neck Depth</td>
                            <td valign="middle" align="center"><strong>:</strong></td>
                            <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['back_neck_depth']; ?>							  </td>
                          </tr>
                            
														<tr>
                              <td valign="top" align="left"> Back Neck Style </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['back_neck_style']; ?>							  </td>
                            </tr>
                                                
                          <tr>
                              <td valign="top" align="left">12. Around Waist</td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['around_waist']; ?>									</td>
                            </tr>
                            <tr>
                              <td valign="top" align="left">13. Around Hips  </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['around_hips']; ?>									</td>
                            </tr>
							                                               
							<tr>
                              <td valign="top" align="left">14. Your Height </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['your_height']; ?>									</td>
                            </tr>
							
							<tr>
                              <td colspan="3" align="left" valign="top"><strong>Salwar Top</strong></td>
                            </tr>
                            <tr>
                              <td valign="top" align="left">1. Kameez Style </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['kameez_style']; ?>									</td>
                            </tr>
							
							<tr>
                              <td valign="top" align="left">2. Kameez Length </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['kameez_length']; ?>									</td>
                            </tr>
                            <tr>
                              <td colspan="3" align="left" valign="top"><strong>Salwar Bottom</strong></td>
                            </tr>
							
							<tr>
                              <td valign="top" align="left"> 1. Salwar/Churidar/Patiala Length </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['salwar_length']; ?>									</td>
                            </tr>
							
							<tr>
                              <td valign="top" align="left"> 2. Salwar Style </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['salwar_style']; ?>									</td>
                            </tr>
							
							<tr>
                              <td valign="top" align="left"> 3. Around Bottom </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['around_bottom']; ?>									</td>
                            </tr>
							<tr>
                              <td colspan="3" align="left" valign="top"><strong>&nbsp;</strong></td>
                            </tr>
							<tr>
                              <td valign="top" align="left"> 1.Around Thigh </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['around_thigh']; ?>									</td>
                            </tr>
							 <tr>
                              <td valign="top" align="left"> 2.Around Knee </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['around_knee']; ?>									</td>
                            </tr>
							
							 <tr>
                              <td valign="top" align="left"> 3.Around Calf </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['around_calf']; ?>									</td>
                            </tr>
							
							
							 <tr>
                              <td valign="top" align="left"> 4.Around Ankle </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['around_ankle']; ?>									</td>
                            </tr>
							
							 <tr>
                              <td valign="top" align="left"> 5.Churidar Style </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
							  <?php echo $mformeasurmentmodel[0]['churidar_style']; ?>									</td>
                            </tr>

							 <tr>
                              <td valign="top" align="left">Instruction </td>
                              <td valign="middle" align="center"><strong>:</strong></td>
                              <td valign="top" align="left" class="ass_text">
								<?php echo $mformeasurmentmodel[0]['instructions']; ?>							  </td>
                            </tr>
							
							
                        </tbody></table>
<?php } }else{?>
        <table>
       
        <tr>
            <td>No record found.</td>
        </tr>

    </table>
<?php } ?>
