<?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
<table cellspacing="0" cellpadding="0" class="ProdListingMain">



			<tbody>
			<tr>

				<td class="breadcrumb">

					<p><a href="#">Home</a> >> <span>My Measurement</span></p>

				</td>

			</tr>


	  <tr>

				<td>

					<table cellspacing="0" cellpadding="0" class="accInfoMain">

						<tbody>
						

						<tr><td>&nbsp;</td></tr>

						<tr><td colspan="2" class="accInfoTxt">My Measurements</td></tr>

						<tr>

							<td class="prevOrder">

								<img width="37" height="41" alt="Previous Measurements" src="http://static.sareez.com/images/measurements-ico.gif">

							</td>

							<td class="tblValign">

								<table cellspacing="0" cellpadding="0" class="MaccountTbl">
								<tbody><tr>
								<td valign="top">
								<table>

									<tbody><tr>

										<td style="padding-left:20px;"><font color="#BF070D">Add New Measurements in Advance</font></td>

									</tr>
									<tr>

										<td style="padding-left:20px;">i.&nbsp;&nbsp;&nbsp;<a href="<?php echo $this->getUrl('measurement/index/blouse')?>">Add Measurement for Blouse and Petticoat</a></td>

									</tr>
									
									<tr>

										<td style="padding-left:20px;">ii.&nbsp;&nbsp;<a href="<?php echo $this->getUrl('measurement/index/salwar')?>">Add Measurement for Salwar or Churidar Kameez</a></td>

									</tr>
									<tr>

										<td style="padding-left:20px;">iii.&nbsp;<a href="<?php echo $this->getUrl('measurement/index/lehenga')?>">Add Measurement for Lehenga Choli</a></td>

									</tr>
									</tbody></table>
									</td>
									</tr>									

								</tbody></table>
							</td>
	<td>
	<table>
	<tbody><tr>

	<td style="padding-left:20px;"><font color="#BF070D">View measurements</font></td>

	</tr>

	<tr>

	<td style="padding-left:20px;">i.&nbsp;&nbsp;&nbsp;<a href="<?php echo $this->getUrl('measurement/index/viewallmeasurement')?>">View all the measurements I have made.</a></td>

	</tr>
	<tr>

	<td style="padding-left:20px;">ii.&nbsp;&nbsp;<a href="<?php echo $this->getUrl('measurement/index/viewblouse')?>">Blouse &amp; Petticoat only.</a></td>

	</tr>
	<tr>

	<td style="padding-left:20px;">iii.&nbsp;<a href="<?php echo $this->getUrl('measurement/index/viewsalwar')?>">Salwar / Churidar only.</a></td>

	</tr>
	<tr>

	<td style="padding-left:20px;">iv.&nbsp;&nbsp;<a href="<?php echo $this->getUrl('measurement/index/viewlehenga')?>">Lehenga Choli only.</a></td>

	</tr>
	</tbody></table>
	</td>
						</tr>
						<tr><td>&nbsp;</td></tr>						
					</tbody>
					</table>

				</td>

			</tr>

      

    </tbody></table>