<?php

if(Mage::getSingleton('customer/session')->isLoggedIn())
 {
	 $customerId = Mage::getModel('customer/session')->getCustomer()->getId();
 }
 
 
$measurement_id	= $this->getRequest()->getParam('m_id');
/*$mforusermodel = Mage::getModel('measurement/measurementforuser')->getCollection()
->AddFieldToFilter('user_id' , $customerId)
->AddFieldToFilter('measurement_id' , $measurement_id )
->getData();
*/


?>

<table style="margin-top:36px">
<tr>
<td>


<?php
$mformeasurmentmodel = Mage::getModel('measurement/measurementforreadymade')->getCollection()
->AddFieldToFilter('readymade_id' ,$measurement_id)
->getData();


if(count($mformeasurmentmodel)>0)
{
 $measurement_type = $mformeasurmentmodel[0]['readymade_type'];

if($measurement_type == 'Blouse-Petticoat')
{

?>
<table width="700" border="0" cellspacing="0" cellpadding="0">		
<tbody>


<tr>
<td width="452" height="22" align="right" valign="top"><strong>Blouse ReadyMade Size</strong></td>
<td width="25" align="center" valign="top">&nbsp;</td>
<td width="223" valign="top" align="center" ></td>
</tr>


<tr>
<td valign="top" align="right"> ReadyMade Size: </td>
<td valign="top" align="center"><strong>:	</strong></td>
<td width="223" align="left" valign="top" class="form_small_ass" ><?php echo $mformeasurmentmodel[0]['blouse_rdmd_reasymade_size'] ?> Inches &nbsp;	

</td>
</tr>


													

<tr>
<td valign="top" align="right">Sleeves lenght </td>
<td valign="top" align="center"><strong>:</strong></td>
<td valign="top" align="left" class="form_small_ass" colspan="1"><?php echo $mformeasurmentmodel[0]['blouse_rdmd_sleeves_length'] ?> Ft &nbsp;


</td>
</tr>

<tr>
<td valign="top" align="right">Blouse Readymade Lengths</td>
<td valign="top" align="center"><strong>:</strong></td>
<td valign="top" align="left" class="form_small_ass" ><?php echo $mformeasurmentmodel[0]['blouse_rdmd_length'] ?> Inches &nbsp;	
</td>
</tr>

<tr>
<td valign="top" align="right">Petticoat Readymade Lengths</td>
<td valign="top" align="center"><strong>:</strong></td>
<td valign="top" align="left" class="form_small_ass" ><?php echo $mformeasurmentmodel[0]['petticoat_rdmd_length'] ?> Inches &nbsp;	
</td>
</tr>
											


<tr>
<td valign="top" align="right" class="form_divider">&nbsp;</td>
<td valign="top" align="center" class="form_divider">&nbsp;</td>
<td valign="top" align="left" class="form_divider" >&nbsp;</td>
</tr>



<tr>
<td valign="top" align="right"> Instructions </td>
<td valign="top" align="center"><strong>:</strong></td>
<td valign="top" align="left" class="form_small_ass" >

  <?php echo $mformeasurmentmodel[0]['instructions'] ?>
</td>
</tr>

<tr>
<td valign="top" align="right" class="form_divider">&nbsp;</td>
<td valign="top" align="center" class="form_divider">&nbsp;</td>
<td valign="top" align="left" class="form_divider" >&nbsp;</td>
</tr>																	
												    
</tbody></table>
<?php
 }
 elseif($measurement_type == 'Lehnga-Choli')
 {
?>
<table width="700" border="0" cellspacing="0" cellpadding="0">		
<tbody>


<tr>
<td width="449" height="22" align="right" valign="top"><strong>Ready Made Lehanga (Top)</strong></td>
<td width="30" align="center" valign="top">&nbsp;</td>
<td width="221" valign="top" align="center" ></td>
</tr>





<tr>
<td valign="top" align="right"> ReadyMade Size: </td>
<td valign="top" align="center"><strong>:</strong></td>
<td width="221" align="left" valign="top" class="form_small_ass" ><?php echo $mformeasurmentmodel[0]['lehenga_rdmd_readymade_size'] ?> Inches &nbsp;	

</td>
</tr>


													

<tr>
<td valign="top" align="right">Height </td>
<td valign="top" align="center"><strong>:</strong></td>
<td valign="top" align="left" class="form_small_ass" colspan="1"><?php echo $mformeasurmentmodel[0]['lehenga_rdmd_height'] ?> Ft &nbsp;

&nbsp;<?php echo $mformeasurmentmodel[0]['lehenga_rdmd_height_2'] ?> Inches &nbsp;
</td>
</tr>

<tr>
<td valign="top" align="right">Sleeve Lengths</td>
<td valign="top" align="center"><strong>:</strong></td>
<td valign="top" align="left" class="form_small_ass" ><?php echo $mformeasurmentmodel[0]['lehenga_rdmd_sleeves_length'] ?> Inches &nbsp;	
	  

</td>
</tr>

<tr>
<td valign="top" align="right">Waist</td>
<td valign="top" align="center"><strong>:</strong></td>
<td valign="top" align="left" class="form_small_ass" ><?php echo $mformeasurmentmodel[0]['lehenga_rdmd_waist'] ?> Inches &nbsp;	
	  

</td>
</tr>

														


<tr>
<td valign="top" align="right" class="form_divider">Choli Length</td>
<td valign="top" align="center" class="form_divider"><strong>:</strong></td>
<td valign="top" align="left" class="form_divider" ><?php echo $mformeasurmentmodel[0]['choli_rdmd_length'] ?> <span class="form_small_ass">Inches</span></td>
</tr>

<tr>
<td valign="top" align="right"> Instructions </td>
<td valign="top" align="center"><strong>:</strong></td>
<td valign="top" align="left" class="form_small_ass" >

 <?php echo $mformeasurmentmodel[0]['instructions'] ?>
</td>
</tr>

<tr>
<td valign="top" align="right" class="form_divider">&nbsp;</td>
<td valign="top" align="center" class="form_divider">&nbsp;</td>
<td valign="top" align="left" class="form_divider" >&nbsp;</td>
</tr>																	
												    
</tbody></table>
<?php
}
else
{

?>
<table width="700" border="0" cellspacing="0" cellpadding="0">		
<tbody>


<tr>
<td width="447" height="22" align="right" valign="top"><strong>Ready Made Salwar (Top)</strong></td>
<td width="35" align="center" valign="top">&nbsp;</td>
<td width="218" valign="top" align="center"></td>
</tr>





<tr>
<td valign="top" align="right"> ReadyMade Size: </td>
<td valign="top" align="center"><strong>: 	</strong></td>
<td valign="top" align="left" class="form_small_ass" ><?php echo $mformeasurmentmodel[0]['suit_rdmd_readymade_size'] ?> Inches &nbsp;	

</td>
</tr>

<tr>
<td valign="top" align="right">Height </td>
<td valign="top" align="center"><strong>:</strong></td>
<td valign="top" align="left" class="form_small_ass" colspan="1"><?php echo $mformeasurmentmodel[0]['suit_rdmd_height'] ?> Ft &nbsp;

&nbsp;<?php echo $mformeasurmentmodel[0]['suit_rdmd_height_2'] ?> Inches &nbsp;
</td>
</tr>

<tr>
<td valign="top" align="right">Sleeve Lengths</td>
<td valign="top" align="center"><strong>:</strong></td>
<td valign="top" align="left" class="form_small_ass" ><?php echo $mformeasurmentmodel[0]['suit_rdmd_sleeves_length'] ?> Inches &nbsp;	
	  

</td>
</tr>

														
<!--

<tr>
<td valign="top" align="right" class="form_divider">&nbsp;</td>
<td valign="top" align="center" class="form_divider">&nbsp;</td>
<td valign="top" align="left" class="form_divider" >&nbsp;</td>
</tr>

	    


<tr>
<td valign="top" height="22" align="right"><strong></strong></td>
<td valign="top" align="center">&nbsp;</td>
<td valign="top" align="left" class="form_small_ass" >&nbsp;</td>
</tr>



-->

<tr>
<td valign="top" align="right"> Instructions </td>
<td valign="top" align="center"><strong>:</strong></td>
<td valign="top" align="left" class="form_small_ass" >

 <?php echo $mformeasurmentmodel[0]['instructions'] ?>
</td>
</tr>

<tr>
<td valign="top" align="right" class="form_divider">&nbsp;</td>
<td valign="top" align="center" class="form_divider">&nbsp;</td>
<td valign="top" align="left" class="form_divider" >&nbsp;</td>
</tr>																	
												    
</tbody></table>
<?php 
}
}
else
{
?>
<table> 
<tr>
<td>
No records found
</td>
</tr>
</table>
<?php
}
?>
</td>
</tr>
</table>