<script type="text/javascript">
//<![CDATA[
var advancedCustomOptions = new AdvancedCustomOptions('<?php echo $this->__($this->helper('emjainteractive_advancedoptions/checkout_cart')->getRemovedMessage())?>', '<?php echo $this->__($this->helper('emjainteractive_advancedoptions/checkout_cart')->getEditedMessage())?>');
advancedCustomOptions.removeLabel = "<?php echo $this->__($this->helper('emjainteractive_advancedoptions/checkout_cart')->getRemoveButtonLabel())?>";
//]]>
</script>
