<?php
  /*
   {{block type="catalog/product_list" template="inchoo/onsale/sale.phtml"}}
   */
?>

<?php
    $_productCollection = Mage::getModel('catalog/product')->getCollection();
    $_productCollection->addAttributeToSelect(array(
                                   'image',
                                   'name',
                                   'short_description'
                                              ))
                        ->addFieldToFilter('visibility', array(
                                    Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
                                    Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                            )) //showing just products visible in catalog or both search and catalog
                        ->addFinalPrice()
//                        ->addAttributeToSort('price', 'asc') //in case we would like to sort products by price
                        ->getSelect()
                        ->where('price_index.final_price < price_index.price')
//                        ->limit(30) //we specify how many products we want to show on this page
//                        ->order(new Zend_Db_Expr('RAND()')) //in case we would like to sort products randomly
                        ;

    Mage::getModel('review/review')->appendSummary($_productCollection);

    $_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php // List mode ?>
<!--        --><?php //if($this->getMode()!='grid'): ?>
            <?php $_iterator = 0; ?>
            <div class="grid-list">
    <?php $_collectionSize = $_productCollection->count() ?>
     <?php $_columnCount = 4; ?>
    <?php // $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
    <?php $_productCollection = $_product->getResource()->getAttribute('exprees_shipping_available')->getFrontend()->getValue($_product); ?> 
						
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item col-xs-6 col-sm-3<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
            
            
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $_product->getImageUrl(); ?>" width="300" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>            
            
            	<?php 
						
							
							if($_productCollection=='7 days'){
							 echo '';
							} else if($_productCollection=='10 days'){
							 echo '';
							} else if($_productCollection=='15 days'){
							 echo '';
							}
						?>
            
            
                
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
					   <div class="buynow_addtocart">
                        <button type="button" title="<?php echo $this->__('Buy Now') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Buy Now') ?></button>
                        <a href="Javascript:void(0)" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" class="buyNow"><img src="http://static.sareez.com/includes/languages/english/images/buttons/shopNow_new.jpg" > </a>
						</div>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a> <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><img src="<?php echo $this->getSkinUrl('images/wish_list.jpg'); ?>"  /></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><div class="separator"></div> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a> <a href="<?php echo $_compareUrl ?>" class="link-compare"><img src="<?php echo $this->getSkinUrl('images/compare.jpg'); ?>"  width="25" /></a>
                            
                            </li>
                        <?php endif; ?>
                         
						
                    </ul>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
  </div>
<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>    </div>
<?php endif; ?>
