<?php 
require_once("app/Mage.php");
$app = Mage::app('');


//$where=" WHERE 1 AND stock_available<=0";
//$where =" WHERE allocationstatus_id = 1 ";
$where =" WHERE 1 ";
if(isset($_REQUEST['flag']) && $_REQUEST['flag']==2){
	
	//print_r($_REQUEST);
	if($_REQUEST['product_sku']!=''){
	  $sku_code=$_REQUEST['product_sku'];
	//$where.=" AND `sku` = '$sku_code'";
	$where.=" AND `sku` LIKE '%$sku_code'";
	}else{
		
		 $orderId=$_REQUEST['order_id'];
		 $SkuCode=$_REQUEST['order_sku'];
		$where.=" AND `sku` = '$SkuCode' AND `increment_order_id` = '$orderId'";	
	}
	
}else{
	$display="none";
}




$conn = mysql_connect("localhost","hbanfvqkdv","tXySfqDmQ3") or die("ERROR::Not connected to SERVER"); 
$db = mysql_select_db("hbanfvqkdv",$conn) or die("ERROR::Not connected to DATABASE");



$write = Mage::getSingleton('core/resource')->getConnection('core_read');
$sql="SELECT * FROM `sales_flat_order_item_stitching` $where";
//echo $sql."KKK";

//exit;
$readresult=$write->query($sql);


?>
<div align="center"><h1>Di-Allocation Status</h1><div>
<table width="100%" border="1" cellpadding="3" cellspacing="3" style="display:<?php echo $display;?>;">

  <tr>
        <td><b>SKU Code</b></td>
        <td><b>Man Model</b></td>
        <td><b>Name</b></td>
        <td><b>Price</b></td>
        <td><b>Manufacture Price</b></td>
       <!-- <td><b>Order Id</b></td>-->
        <!--<td><b>Color</b></td>-->
        <td><b>Stock</b></td>
        <!--<td><b>Qty</b></td>-->
         <td class="order_test"><b>Order Id's</b></td>
        <td><b>Image</b></td>
  </tr>


<?php


while ($rowff = $readresult->fetch() ) {
	$sku_code = $rowff['sku'];
	//echo "<pre>";
	//print_r($rowff);
}

//echo $sku_code;


if($_REQUEST['product_sku']!=''){
	
	$sku=$_REQUEST['product_sku'];
	
$collection_sku = Mage::getResourceModel('catalog/product_collection')
   ->addAttributeToFilter('sku', array('like' => '%'.$sku.'%'))
  // ->addAttributeToFilter('status', 1)
  // ->addAttributeToFilter('visibility', 4)
    ->load();
	//print_r($collection_sku);
	foreach($collection_sku as $p_sku) {
		//echo "chinmay";
	  $sku_code=$p_sku->getSku();
	//}
	//echo "aaa";
//exit;
	
	$product = Mage::getModel('catalog/product')->loadByAttribute('sku',$sku_code);
//$product = Mage::getModel('catalog/product')->loadByAttribute('manufacturer_design',$design_no);
$stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($product);
if($product){
?>
<tr>
    <td><?php echo $product->getSku();//echo $sku_code; ?></td>
    <td><?php echo $product->getManufacturerDesign(); //echo $manufacturer; ?></td>
    <td><?php echo $product->getName(); ?></td>
    <td><?php echo '$'.$product->getPrice(); ?></td>
    <td><?php echo 'Rs.'.$product->getMsrp();?></td>
   <!-- <td><?php //echo $order_id; ?></td>-->
    <!--<td><?php //echo $product->getAttributeText('color'); ?></td>-->
    <td><?php  $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($product); echo $stock->getQty(); 
	//print_r($stock->getData())
	
	?></td>
    
     <!--<td><?php //echo $fffqty1; ?></td>-->
    <td class="order_test">
	
	<?php 
	$sql_ord = "SELECT increment_order_id FROM `sales_flat_order_item_stitching` where sku = '".$product->getSku()."' ";
	$readresult_ord=$write->query($sql_ord);
	$h=0;
	while ($rowff_ord = $readresult_ord->fetch() ) {
		
		echo $rowff_ord['increment_order_id'].",";
		if($h%5==0){
			echo "<br>";
			}
		$h++;
	}
 	?>
    <br />
    <br>
   <b> Total Qty : <?php echo $h; ?></b>
 </td>
 
    <td>
    <img border="0" width="100" src=<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl( $product->getSmallImage() );?>>
    <br>
    <a href="<?php echo $imageCacheUrl = Mage::helper('catalog/image')->init($product, 'thumbnail');?>" target="_blank">
    View Product Image
    </a>
    
    <!--<a href="<?php echo $product->getProductUrl();?>"><img border="0" width="100" src=<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl( $product->getSmallImage() );?>></a>-->
    </td>
<tr>
 <?php
  }
 }
 
?>
  
<?php 
} elseif ($_REQUEST['order_id']!='' || $_REQUEST['order_sku']!='' ){
	
 $orderId=$_REQUEST['order_id'];
 $SkuCode=$_REQUEST['order_sku'];

//$collection = Mage::getModel('sorder/sorder')->getCollection();	
	/*$collection = Mage::getModel('sorder/sorder')
					->getCollection()
					->addAttributeToSelect('*')
					->addAttributeToFilter('sku', $_REQUEST['order_sku'])
    				->addAttributeToFilter('increment_order_id', $_REQUEST['order_id'])
                    ->load();*/	
$sql_order = "select * from `sales_flat_order_item_stitching` where increment_order_id LIKE '%$orderId%' AND sku LIKE '%$SkuCode%' ";
	$readresult_order=$write->query($sql_order);
	while ($p = $readresult_order->fetch() ) {
		
		//echo $p['increment_order_id'].",";
	
   // echo $p->getName()."\n";
	  $sku_p=$p['sku'];
	// echo "<pre>";
	// print_r($p);
//echo "chinmay";
	//exit;

$product = Mage::getModel('catalog/product')->loadByAttribute('sku',$sku_p);
//$product = Mage::getModel('catalog/product')->loadByAttribute('manufacturer_design',$design_no);
$stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($product);
if($product){
?>
<tr>
    <td><?php echo $product->getSku();//echo $sku_code; ?></td>
    <td><?php echo $product->getManufacturerDesign(); //echo $manufacturer; ?></td>
    <td><?php echo $product->getName(); ?></td>
    <td><?php echo '$'.$product->getPrice(); ?></td>
    <td><?php echo 'Rs.'.$product->getMsrp();?></td>
   <!-- <td><?php //echo $order_id; ?></td>-->
    <!--<td><?php //echo $product->getAttributeText('color'); ?></td>-->
    <td><?php  $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($product); echo $stock->getQty(); 
	//print_r($stock->getData())
	
	?></td>
    
     <!--<td><?php //echo $fffqty1; ?></td>-->
     <td class="order_test">
     <?php 
	$sql_ord = "SELECT increment_order_id FROM `sales_flat_order_item_stitching` where sku = '".$p['sku']."' AND increment_order_id='".$p['increment_order_id']."' ";
	$readresult_ord=$write->query($sql_ord);
	$h=0;
	while ($rowff_ord = $readresult_ord->fetch() ) {
		
		echo $rowff_ord['increment_order_id'].",";
		
		if($h%5==0){
			echo "<br>";
			}
		$h++;
		
	}
	
	
 	?>
    <br />
    <br />
    <b>Total Qty : <?php echo $h; ?></b>
    </td>
    
    <td>
     <img border="0" width="100" src=<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl( $product->getSmallImage() );?>>
    <br>
        <a href="<?php echo $imageCacheUrl = Mage::helper('catalog/image')->init($product, 'thumbnail');?>" target="_blank">
    View Product Image
    </a>

    
   
    
    </td>
<tr>
 <?php
 // }
 }
	
}

 
 } else{
?>
<tr>
        <td colspan="10" align="center"><span style="color:red;">No Record(s) Found!!</span></td>
  </tr>
  
  <?php } ?>
</table>
 

<form name="form2" method="get" action="" >
<?php /*?><form name="form2" method="get" action="<?php echo $_SERVER['PHP_SELF']; ?>" ><?php */?>
<input type="hidden" name="product_sku" id="product_sku" value="<?php echo $_REQUEST['product_sku'];?>"/>
<input type="hidden" name="order_id" id="order_id" value="<?php echo $_REQUEST['order_id'];?>"/>
<input type="hidden" name="order_sku" id="order_sku" value="<?php echo $_REQUEST['order_sku'];?>"/>
<table width="100%" border="0" cellspacing="3" cellpadding="3">
  <tr>
    <td width="33%">&nbsp;</td>
    <td width="2%">&nbsp;</td>
    <td width="65%">&nbsp;</td>
  </tr>
  
  
  <tr>
    <td align="right"><b><?php echo $this->__('Order Id :') ?></b></td>
    <td>&nbsp;</td>
    <td>
    <input type="text" name="order_id" id="order_id" value="<?php echo $_REQUEST['order_id'] ?>"/>
   
</td>
  </tr>
  
  
  <tr>
    <td align="right"><b><?php echo $this->__('Product Sku :') ?></b></td>
    <td>&nbsp;</td>
    <td><input type="text" name="order_sku" id="order_sku" value="<?php echo $_REQUEST['order_sku'] ?>"/></td>
  </tr>
  <tr>
  
  
  
  
  
    <tr>
    <td align="right"></td>
    <td>&nbsp;</td>
    <td><b>Or</b></td>
  </tr>
  
  
  <tr>
    <td align="right"><b><?php echo $this->__('Product Sku :') ?></b></td>
    <td>&nbsp;</td>
    <td><input type="text" name="product_sku" id="product_sku" value="<?php echo $_REQUEST['product_sku'] ?>"/></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>
      <input type="submit" name="button" id="button" value="Submit">&nbsp;&nbsp;
      <!--<input type="submit" name="button2" id="button2" value="Order Process">--></td>
 <?php /*?> <input type="hidden" name="current_url" value="<?php echo 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']; ?>" ><?php */?>
  <input type="hidden" name="flag" value="2" />
  
  </tr>
</table>
</form>

<?php 
if(isset($_REQUEST['flag']) && $_REQUEST['flag']==9){


$product_sku = $_REQUEST['product_sku'];
 $stock_enter_text = $_REQUEST['stock_enter_text'];
 $quantity = ($_REQUEST['quantity']+$stock_enter_text);


$aid=$_REQUEST['id'];
/*echo $_REQUEST['stock_enter_text'];

if(strpos($aid,':') !== false) {
    echo 'true';
}else{
	 echo 'false';
}
*/

if($_REQUEST['tot_cel']=='' && $_REQUEST['quantity']==''){

$orderId=$_REQUEST['order_id'];
$SkuCode=$_REQUEST['order_sku'];

$sql_order1 = "select * from `sales_flat_order_item_stitching` where increment_order_id LIKE '%$orderId%' AND sku LIKE '%$SkuCode%' ";
	$readresult_order1=$write->query($sql_order1);
	while ($p1 = $readresult_order1->fetch() ) {
	  $sku_p=$p1['sku'];
	  
	  $productQty = Mage::getModel("catalog/product")->getIdBySku( $sku_p ); 
	$stockItem =Mage::getModel('cataloginventory/stock_item')->loadByProduct($productQty);
	//echo "<pre>";
	if($stockItem->getQty() >= $_REQUEST['stock_enter_text']){
		
			foreach($_REQUEST['id'] as $selected) {
		
		//print_r($selected);
			$order_id = explode(":", $selected);
			
			$write = Mage::getSingleton('core/resource')->getConnection('core_write');
			$result=$write->query("SELECT increment_id FROM `sales_flat_order` WHERE `entity_id` =".$order_id[1]);
			$row = $result->fetch();
		
			$sql10="UPDATE `sales_flat_order_item_stitching` SET `allocationstatus_id`='1',`allocation_date`='".date("Y-m-d")."', `download_status_process` = 'Y',`allocated_by` = 'Manual' WHERE `id`='".$selected."'";
					  //echo $sql10; die;
					   mysql_query($sql10) or die("ERROR10::".mysql_error());
					  
		
		}
	  
	}
	
	$countId = count($_REQUEST['id']);
		
		
		  $stock_quantity = ($_REQUEST['quantity']+$countId);
		
		$product_id = Mage::getModel("catalog/product")->getIdBySku( $sku_p ); 
		
		$stockItem =Mage::getModel('cataloginventory/stock_item')->loadByProduct($product_id);
		$stockItem->setData('qty', (integer)$stock_quantity);
		 $stockItem->setData('', (integer)$stock_quantity);
		$stockItem->save();
		
		
	
	
	}

	

	
}elseif($_REQUEST['stock_enter_text']=='' && strpos($aid,':') !== false) {
	$product_sku=$_REQUEST['product_sku'];
		$collection_sku = Mage::getResourceModel('catalog/product_collection')
  						 ->addAttributeToFilter('sku', array('like' => '%'.$product_sku.'%'))
    					 ->load();
	
	foreach($collection_sku as $p_sku) {
		
		$sku_code=$p_sku->getSku();
		//$product_id=$p_sku->getId();
		$productQty = Mage::getModel("catalog/product")->getIdBySku( $sku_code ); 
		$stockItem =Mage::getModel('cataloginventory/stock_item')->loadByProduct($productQty);
		if($stockItem->getQty() >= $_REQUEST['stock_enter_text']){
			foreach($_REQUEST['id'] as $selected) {
			$order_id = explode(":", $selected);
			
			$sql1011="UPDATE `sales_flat_order_item_stitching` SET `allocationstatus_id`='1',`allocation_date`='".date("Y-m-d")."', `download_status_process` = 'Y',`allocated_by` = 'Manual' WHERE `id`='".$selected."'";
					  //echo $sql10; die;
					   mysql_query($sql1011) or die("ERROR10::".mysql_error());
			}
			$countId = count($_REQUEST['id']);
			$stock_quantity = ($_REQUEST['quantity']+$countId);
			$product_id = Mage::getModel("catalog/product")->getIdBySku( $sku_code ); 
			$stockItem =Mage::getModel('cataloginventory/stock_item')->loadByProduct($product_id);
			$stockItem->setData('qty', (integer)$stock_quantity);
			$stockItem->setData('', (integer)$stock_quantity);
			$stockItem->save();
		}
		
	}
	
} else if($_REQUEST['stock_enter_text']!=='' && strpos($aid,':') !== false) {
			echo "3333333333333333333333";exit;
	
	$productQty = Mage::getModel("catalog/product")->getIdBySku( $product_sku ); 
	$stockItem =Mage::getModel('cataloginventory/stock_item')->loadByProduct($productQty);
	//echo "<pre>";
	if($stockItem->getQty()<=0){
	//exit;
	 $countId = count($_REQUEST['id']);
	

		foreach($_REQUEST['id'] as $selected) {
		
		//if($key == $_REQUEST['stock_enter_text']){
			$order_id = explode(":", $selected);
			
			$write = Mage::getSingleton('core/resource')->getConnection('core_write');
			$result=$write->query("SELECT increment_id FROM `sales_flat_order` WHERE `entity_id` =".$order_id[1]);
			$row = $result->fetch();
		
			$sql10="UPDATE `sales_flat_order_item_stitching` SET `allocationstatus_id`='2',`allocation_date`='".date("Y-m-d")."', `download_status_process` = 'N' ,`allocated_by` = 'Manual' WHERE `id`='".$selected."'";
					  // echo $sql10; die;
					   mysql_query($sql10) or die("ERROR10::".mysql_error());
					  
			//}
		}
		
				   
		
		$stock_quantity = ($_REQUEST['quantity']+$stock_enter_text);
		$product_id = Mage::getModel("catalog/product")->getIdBySku( $product_sku ); 
		
		$stockItem =Mage::getModel('cataloginventory/stock_item')->loadByProduct($product_id);
		$stockItem->setData('qty', (integer)$stock_quantity);
		 $stockItem->setData('', (integer)$stock_quantity);
		$stockItem->save();
		
		if($quantity > 0)
		{
			$products_express ='33';
			$simpleProduct = Mage::getModel('catalog/product')->loadByAttribute('sku',$product_sku);	
					if($simpleProduct) {
						$simpleProduct->setExpreesShippingAvailable($products_express);
						$simpleProduct->save();
			}
		}
	}elseif($stockItem->getQty()>=0){
		
	  $countId = count($_REQUEST['id']);
	

		
		
				   
		if($stock_enter_text==$countId){
			//echo "11111";exit;
			
			foreach($_REQUEST['id'] as $selected) {
		
		//print_r($selected);
			$order_id = explode(":", $selected);
			
			$write = Mage::getSingleton('core/resource')->getConnection('core_write');
			$result=$write->query("SELECT increment_id FROM `sales_flat_order` WHERE `entity_id` =".$order_id[1]);
			$row = $result->fetch();
		
			$sql10="UPDATE `sales_flat_order_item_stitching` SET `allocationstatus_id`='2',`allocation_date`='".date("Y-m-d")."', `download_status_process` = 'N',`allocated_by` = 'Manual'  WHERE `id`='".$selected."'";
					  //echo $sql10; die;
					   mysql_query($sql10) or die("ERROR10::".mysql_error());
					  
		
		}
		
		
		
			
	
		}elseif($stock_enter_text > $countId){
			
			//echo "2222";exit;
			foreach($_REQUEST['id'] as $key=>$selected) {
		
		
			$order_id = explode(":", $selected);
			
			$write = Mage::getSingleton('core/resource')->getConnection('core_write');
			$result=$write->query("SELECT increment_id FROM `sales_flat_order` WHERE `entity_id` =".$order_id[1]);
			$row = $result->fetch();
		
			$sql10="UPDATE `sales_flat_order_item_stitching` SET `allocationstatus_id`='2',`allocation_date`='".date("Y-m-d")."', `download_status_process` = 'N',`allocated_by` = 'Manual'  WHERE `id`='".$selected."'";
					  // echo $sql10; die;
					   mysql_query($sql10) or die("ERROR10::".mysql_error());
					  
		}
		
		
			$qtyVal= $stock_enter_text-$countId;
		$stock_quantity = ($_REQUEST['quantity']+$qtyVal);
		$product_id = Mage::getModel("catalog/product")->getIdBySku( $product_sku ); 
		
		$stockItem =Mage::getModel('cataloginventory/stock_item')->loadByProduct($product_id);
		$stockItem->setData('qty', (integer)$stock_quantity);
		 $stockItem->setData('', (integer)$stock_quantity);
		$stockItem->save();
		}elseif($stock_enter_text < $countId){
			
			//echo "333";exit;
			foreach($_REQUEST['id'] as $key=>$selected) {
		
		//if($key==$_REQUEST['stock_enter_text']){
			//echo "test";exit;
			$order_id = explode(":", $selected);
			
			$write = Mage::getSingleton('core/resource')->getConnection('core_write');
			$result=$write->query("SELECT increment_id FROM `sales_flat_order` WHERE `entity_id` =".$order_id[1]);
			$row = $result->fetch();
		
			$sql10="UPDATE `sales_flat_order_item_stitching` SET `allocationstatus_id`='2',`allocation_date`='".date("Y-m-d")."', `download_status_process` = 'N',`allocated_by` = 'Manual'  WHERE `id`='".$selected."'";
					  // echo $sql10; die;
					   mysql_query($sql10) or die("ERROR10::".mysql_error());
					  
			//}
		}
		
		
		
			$qtyVal= $countId-$stock_enter_text;
		$stock_quantity = ($_REQUEST['quantity']-$qtyVal);
		$product_id = Mage::getModel("catalog/product")->getIdBySku( $product_sku ); 
		
		$stockItem =Mage::getModel('cataloginventory/stock_item')->loadByProduct($product_id);
		$stockItem->setData('qty', (integer)$stock_quantity);
		 $stockItem->setData('', (integer)$stock_quantity);
		$stockItem->save();
		
		
		
		
		}
		
		if($quantity > 0)
		{
			$products_express ='33';
			$simpleProduct = Mage::getModel('catalog/product')->loadByAttribute('sku',$product_sku);	
					if($simpleProduct) {
						$simpleProduct->setExpreesShippingAvailable($products_express);
						$simpleProduct->save();
			}
		}
		
		
	}
		
		

} else {
	
	
	//($_REQUEST['stock_enter_text']=='' && strpos($aid,':')!== true) 
			echo "22222222222222222111111111111";exit;
		 $stock_quantity = ($_REQUEST['quantity']+$stock_enter_text);
		$product_id = Mage::getModel("catalog/product")->getIdBySku( $product_sku ); 
		
		$stockItem =Mage::getModel('cataloginventory/stock_item')->loadByProduct($product_id);
		$stockItem->setData('qty', (integer)$stock_quantity);
		 $stockItem->setData('', (integer)$stock_quantity);
		$stockItem->save();
		
		if($quantity > 0)
		{
			$products_express ='33';
			$simpleProduct = Mage::getModel('catalog/product')->loadByAttribute('sku',$product_sku);	
					if($simpleProduct) {
						$simpleProduct->setExpreesShippingAvailable($products_express);
						$simpleProduct->save();
			}
		}
		
}


}

?>

<form name="form3" method="get" action="<?php echo $_SERVER['PHP_SELF']; ?>" >
<input type="hidden" name="product_sku" id="product_sku" value="<?php echo $_REQUEST['product_sku'];?>" />
<input type="hidden" name="order_sku" id="order_sku" value="<?php echo $_REQUEST['order_sku'];?>" />
<input type="hidden" name="order_id" id="order_id" value="<?php echo $_REQUEST['order_id'];?>" />

<?php
$product = Mage::getModel('catalog/product')->loadByAttribute('sku',$sku_code);
$stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($product); 
?>
<input type="hidden" name="quantity" value="<?php echo $stock->getQty(); ?>" />
<input type="hidden" name="id" value="<?php echo $stock->getId(); ?>" />

<table width="100%" border="1" cellpadding="3" cellspacing="3" style="display:<?php echo $display;?>;">
  <tr>
  <td><b>Order Id</b></td>
   <td><b>Date</b></td>
        <td><b>SKU Code</b></td>
        
        <td><b>Man Model</b></td>
        <td><b>Name</b></td>
        <td><b>Price</b></td>
        
        <td><b>Payment</b></td>
        <td><b>Order Status</b></td>
        <td><b>Options</b></td>
        <!--<td><b>Color</b></td>-->
        <td><b>Stock</b></td>
        <td><b>R/Qty</b></td>
       
        <td><b>&nbsp;</b></td>
  </tr>

<?php


if($_REQUEST['product_sku']!=''){
	 $sku_code=$_REQUEST['product_sku'];
	//$where1=" WHERE 1 AND `stock_available` <=0";
	$where1=" WHERE 1 ";
	//$where1.=" AND `sku` = '$sku_code'";
	$where1.=" AND `sku` LIKE '%$sku_code'";
	}else{
		$where1=" WHERE 1 ";
		 
		 $orderId=$_REQUEST['order_id'];
		 $SkuCode=$_REQUEST['order_sku'];
		$where1.=" AND `sku` LIKE '%$SkuCode%' AND `increment_order_id` LIKE '%$orderId%'";
	}




$sql1="SELECT * FROM `sales_flat_order_item_stitching` $where1";
$readresult1=$write->query($sql1);

$y=1;
if(count($readresult1)>0){
while ($rowRes = $readresult1->fetch() ) {
	
	$sku_code = $rowRes['sku'];
$product = Mage::getModel('catalog/product')->loadByAttribute('sku',$sku_code);
 $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($product); 
 
//if($stock->getQty()<=0 && $rowRes['allocationstatus_id']!=2){
	if($rowRes['allocationstatus_id']==2){
	//echo "chinmay";exit;
?>
<tr>
<td><?php echo $rowRes['increment_order_id'];?></td>
 <td><?php echo $rowRes['order_date']; ?></td>
    <td><?php echo $rowRes['sku']; ?></td>
   
    <td><?php echo $rowRes['manufacturer_design']; ?></td>
    <td><?php echo $product->getName(); ?></td>
    <td><?php echo "$ ".$product->getPrice(); ?></td>
    
    <td><?php echo $rowRes['payment_method'];?></td>
    <td><?php echo $rowRes['order_status'];?></td>
    <td><?php echo $rowRes['option_value'];?></td>
    <!--<td><?php //echo $product->getAttributeText('color'); ?></td>-->
    <td><?php echo $stock->getQty(); 
	//print_r($stock->getData())	
	?>
    </td>
    <td>1<?php //echo $rowRes['r_quantity']; ?></td>    
   
    <td>

    <input type="checkbox" name="id[]" id="id" value="<?php echo $rowRes['id'].":".$rowRes['order_id'];?>" />
    </td>
<tr>
 <?php
  }
  $y++;
} }else {
?>
  <tr>
        <td align="center" colspan="10"><span style="color:red;">No Record(s) Found!!</span></td>
  </tr>

<?php } ?>
</table>


<table width="100%" border="0" cellspacing="3" cellpadding="3" style="display:<?php echo $display;?>;">

 <div id="stock_enter_text"></div>
 <div id="demo"></div>
  <tr>
    <td width="33%">&nbsp;</td>
    <td width="2%">&nbsp;</td>
    <td width="65%">&nbsp;</td>
  </tr>

  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>
        <input type="submit" name="button2" id="button2" value="Submit" onClick='return submitRegestrationForm()'>&nbsp;&nbsp;
        <input type="hidden" name="tot_cel" value=<?php echo $x; ?> >
      </td>
       
        <input type="hidden" name="flag" value="9" />
  </tr>
</table>

</form>
