<?php /* ?>
    <script language="javascript" type="text/javascript">setTimeout("location.reload();",20000);</script>
<?php */ ?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl("easymaintanance/css/easymaintanance.css") ?>">
<?php $storeId = Mage::app()->getStore()->getStoreId(); ?>
<html>
<title>Store Maintenance</title>

<?php
    $date =  Mage::getStoreConfig('easymaintanance/timer/timer_date',$storeId);
    $formatedDate = date('m/d/Y',strtotime($date));
    $date = explode('/', $formatedDate);
    $year = $date[2];
    $month = $date[0];
    $day = $date[1];
    $hour = Mage::getStoreConfig('easymaintanance/timer/timer_hour',$storeId);
    $min = Mage::getStoreConfig('easymaintanance/timer/timer_min',$storeId);
?>
<?php
    $maintenancePage = trim(Mage::getStoreConfig('easymaintanance/general/maintenanceHtml',$storeId));
    echo $maintenancePage;
?>
<?php if(Mage::getStoreConfig('easymaintanance/timer/timer_enabled',$storeId) == 1): ?>
<div class="message clearfix" id="timer-text">
    <?php $text = Mage::getStoreConfig('easymaintanance/timer/timer_text',$storeId); ?>
    <h2 id="launch-text"><?php echo $text; ?></h2>
</div>



<script type="text/javascript">

    var current="Time is over!";    
    var year='<?php echo $year; ?>';    
    var month='<?php echo $month; ?>';      
    var day='<?php echo $day; ?>';       
    var hour='<?php echo $hour; ?>';      
    var minute='<?php echo $min; ?>';    
    //    DO NOT CHANGE THE CODE BELOW!
    var montharray=new Array("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec");
    function countdown(yr,m,d,hr,min){

        theyear=yr;themonth=m;theday=d;thehour=hr;theminute=min;
        var today=new Date();
        var todayy=today.getYear();
        if (todayy < 1000)
            todayy+=1900;
        var todaym=today.getMonth();
        var todayd=today.getDate();
        var todayh=today.getHours();
        var todaymin=today.getMinutes();
        var todaysec=today.getSeconds();
        var todaystring=montharray[todaym]+" "+todayd+", "+todayy+" "+todayh+":"+todaymin+":"+todaysec;
        var futurestring=montharray[m-1]+" "+d+", "+yr+" "+hr+":"+min+":"+"00";
        var dd=Date.parse(futurestring)-Date.parse(todaystring);
        var dday=Math.floor(dd/(60*60*1000*24)*1);
        var dhour=Math.floor((dd%(60*60*1000*24))/(60*60*1000)*1);
        var dmin=Math.floor(((dd%(60*60*1000*24))%(60*60*1000))/(60*1000)*1);
        var dsec=Math.floor((((dd%(60*60*1000*24))%(60*60*1000))%(60*1000))/1000*1);
        if(dday<=0&&dhour<=0&&dmin<=0&&dsec<=0){

            document.getElementById('timer-text').style.display="none";
            document.getElementById('timer-table').style.display="none";
            return;
        }
        else {
            document.getElementById('count2').style.display="none";
            document.getElementById('dday').innerHTML=dday;
            document.getElementById('dhour').innerHTML=dhour;
            document.getElementById('dmin').innerHTML=dmin;
            document.getElementById('dsec').innerHTML=dsec;
            setTimeout("countdown(theyear,themonth,theday,thehour,theminute)",1000);
        }

    }
</script>

    <body onLoad="countdown(year,month,day,hour,minute)">
        <div class="countdown" >
            <div class="timer" id="timer-table">
                <div class="numbers" id="count2" style="padding: 5px 0 0 0; "></div>
                <div><strong id="dday"></strong>Days</div>
                <div><strong id="dhour"></strong>Hours</div>
                <div><strong id="dmin"></strong>Minutes</div>
                <div class="last"><strong id="dsec"></strong>Seconds</div>
            </div>
        </div>
    </body>
    <?php endif; ?>

<?php
    /*$date1 = date("Y-m-d H:i:s", Mage::getModel('core/date')->timestamp(time()));
    $date2 = Mage::getStoreConfig('easymaintanance/timer/timer_date',$storeId)." ".$hour.":".$min.":"."00";
    Mage::helper('easymaintanance')->dateDiff($date2, $date1);*/
?>

<?php if(Mage::getStoreConfig('easymaintanance/contactus/active',$storeId) == 1): ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl("easymaintanance/css/popup.css") ?>">
    <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS)."prototype/prototype.js" ?>"></script>
    <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS)."prototype/effects.js" ?>"></script>
    <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS)."prototype/validation.js" ?>"></script>
    <script src="<?php echo $this->getSkinUrl("easymaintanance/js/popup.js") ?>"></script>
    <?php echo  Mage::getSingleton('core/layout')->createBlock('core/template')->setTemplate('easymaintanance/popup_html.phtml')->toHtml(); ?>
    <?php endif; ?>
</html>