<?php
/**
 * GoMage Social Connector Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013-2015 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.2.0
 * @since        Class available since Release 1.0.0
 */
?>
<?php
	$services = Mage::helper('gomage_social')->getServices($this->getPlace());
?>
<?php if (count($services)) : ?>
	<?php if ($this->getUsedList()): ?><li class="last gs-list"><?php endif; ?>
	<ul class="gs-login <?php if(Mage::getConfig()->getModuleConfig('Enterprise_Enterprise' )): ?>gs-login-ee<?php endif; ?> gs-login-<?php echo $this->getPlace() ?>">
		<?php
			end($services);
        	$last_type = key($services);
			
			foreach ($services as $type => $value) {
				echo $this->getServiceBlock($type, $type == $last_type);
			}
		?>
	</ul>
	<?php if ($this->getUsedList()) : ?></li><?php endif; ?>
<?php endif; ?>
