<?php
/**
 * GoMage Social Connector Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2013-2015 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.2.0
 * @since        Class available since Release 1.1.0
 */
?>
<li <?php if ($this->is_last): ?>class="last"<?php endif; ?>>
    <a href="<?php echo $this->getUrl('gomage_social/'.$this->service.'/login', array('_secure' => true, 'gs_url' => Mage::helper('core')->urlEncode(Mage::helper('core/url')->getCurrentUrl())));  ?>" title="<?php echo $this->getText($this->service) ?>">
        <?php if (($image = $this->getImage($this->service)) && ($this->getLoginType($this->service) == GoMage_Social_Model_Adminhtml_System_Config_Source_Login_Type::IMAGE)): ?>
            <img src="<?php echo $image ?>" alt="<?php echo $this->getText($this->service) ?>" />
        <?php else: ?>
            <?php echo $this->getText($this->service) ?>
        <?php endif; ?>
    </a>
</li>