<?php $_option = $this->getOption() ?>
<?php $_quoteItem = $this->getQuoteItem() ?>
<p><?php echo  $this->htmlEscape($_option->getTitle()) ?><?php if ($_option->getIsRequire()): ?><span class="required">&nbsp;*</span><?php endif; ?></p>

    <?php echo $this->getValuesHtml() ?>
    <?php if ($_option->getIsRequire()): ?>
        <?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_RADIO || $_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_CHECKBOX): ?>
            <span id="options-<?php echo $_quoteItem->getId() ?>-<?php echo $_option->getId() ?>-container"></span>
    <?php endif; ?>
<?php endif;?>

<br>
