<div class="content-header">
    <h3 class="icon-head"><?php echo $this->getHeader() ?></h3>
    <p class="content-buttons form-buttons">
        <?php if($this->getItemId()): ?>
            <?php echo $this->getChildHtml('delete_button') ?>
        <?php endif ?>
        <?php echo $this->getChildHtml('save_button') ?>
    </p>
</div>
<?php echo $this->getTabsHtml() ?>

<iframe name="iframeSave" style="display:none; width:100%;" src="<?php echo $this->getJsUrl() ?>blank.html"></iframe>
<form target="iframeSave" id="edit_form" action="<?php echo $this->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
    <div class="no-display">
        <input type="hidden" name="isIframe" value="1" />
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
        <input type="hidden" name="active_tab_id" id="active_tab_id" value="" />
    </div>
    <div id="item_tab_content"></div>
</form>
<script type="text/javascript">
editForm = new varienForm('edit_form');
<?php if($this->isAjax() && ($block = $this->getLayout()->getBlock('tabs')) && ($_tabsJsObject=$block->getJsObjectName())): ?>
    <?php echo $_tabsJsObject ?>.moveTabContentInDest();
    if (<?php echo $_tabsJsObject ?>.activeTab) {
        $('active_tab_id').value = <?php echo $_tabsJsObject ?>.activeTab.id;
    }
    $('active_tab_id').tabsJsObject = <?php echo $_tabsJsObject ?>;
<?php endif; ?>
</script>
