<?php 
require_once("app/Mage.php");
$app = Mage::app('');

$display="none";
$where=" WHERE 1 AND stock_available<=0";
if(isset($_REQUEST['flag']) && $_REQUEST['flag']==2){
	$sku_code=$_REQUEST['product_sku'];
	$where.=" AND `sku` = '$sku_code'";
	$display="block";
}

include '../db/connection.php';
$write = Mage::getSingleton('core/resource')->getConnection('core_write');
$sql="SELECT * FROM `ordercsv` $where";
//echo $sql."KKK";
$readresult=$write->query($sql);
?>

<table width="100%" border="1" cellpadding="3" cellspacing="3" style="display:<?php echo $display;?>;">

  <tr>
        <td><b>SKU Code</b></td>
        <td><b>Man Model</b></td>
        <td><b>Name</b></td>
        <td><b>Price</b></td>
        <td><b>Manufacture Price</b></td>
        <td><b>Order Id</b></td>
        <td><b>Color</b></td>
        <td><b>Stock</b></td>
        <td><b>Qty</b></td>
        <td><b>Image</b></td>
  </tr>


<?php
if(count($readresult)> 0){
$qty='';
$order='';	
while ($row = $readresult->fetch() ) {
	$productId = $row['sku'];
	$manufacturer = $row['manufacturer'];
	$product_name = $row['product_name'];
	$order = $order.",".$row['order_id'].'<br>';
	$qty = $qty.$row['quantity'].'<br>';
}

$order_id = ltrim($order,",");
$fffqty1=ltrim($qty,",");
$product = Mage::getModel('catalog/product')->loadByAttribute('sku',$productId);
 
if($product){
?>
<tr>
    <td><?php echo $productId; ?></td>
    <td><?php echo $manufacturer; ?></td>
    <td><?php echo $product_name; ?></td>
    <td><?php echo $product->getPrice(); ?></td>
    <td>&nbsp;</td>
    <td><?php echo $order_id; ?></td>
    <td><?php echo $product->getAttributeText('color'); ?></td>
    <td><?php  $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($product); echo $stock->getQty(); 
	//print_r($stock->getData())
	
	?></td>
    
     <td><?php echo $fffqty1; ?></td>
    
    <td><img border="0" width="100" src=<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl( $product->getSmallImage() );?>></td>
<tr>
 <?php
  }
 	
} else {
?>
  <tr>
        <td colspan="9"><b>No Record(s) Found!!</b></td>
  </tr>
<?php }?>

</table>
 


<form name="form2" method="get" action="<?php echo $_SERVER['PHP_SELF']; ?>" >
<input type="hidden" name="product_sku" id="product_sku" value="<?php echo $_REQUEST['product_sku'];?>"/>
<table width="100%" border="0" cellspacing="3" cellpadding="3">
  <tr>
    <td width="33%">&nbsp;</td>
    <td width="2%">&nbsp;</td>
    <td width="65%">&nbsp;</td>
  </tr>
  <tr>
    <td align="right"><b><?php echo $this->__('Product Sku :') ?></b></td>
    <td>&nbsp;</td>
    <td><input type="text" name="product_sku" id="product_sku" value=""/>


   </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>
      <input type="submit" name="button" id="button" value="Submit">&nbsp;&nbsp;
      <!--<input type="submit" name="button2" id="button2" value="Order Process">--></td>
  <input type="hidden" name="current_url" value="<?php echo 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']; ?>" >
  <input type="hidden" name="flag" value="2" />
  
  </tr>
</table>

</form>
<?php 
echo $stock_enter_text=$_REQUEST['stock_enter_text'];
print_r($_REQUEST['update_qty']);
print_r($_REQUEST['chechkid']);



?>





<form name="form3" method="get" action="<?php //echo $_SERVER['PHP_SELF']; ?>" >
<input type="hidden" name="product_sku" id="product_sku" value="<?php echo $_REQUEST['product_sku'];?>"/>

<table width="100%" border="1" cellpadding="3" cellspacing="3">

  <tr>
        <td><b>SKU Code</b></td>
        <td><b>Man Model</b></td>
        <td><b>Name</b></td>
        <td><b>Price</b></td>
      <!--  <td><b>Manufacture Price</b></td>-->
        <td><b>Order Id</b></td>
        <td><b>Color</b></td>
        <td><b>Stock</b></td>
        <td><b>R/Qty</b></td>
        <td><b>A/Qty</b></td>
         <td><b></b></td>
  </tr>


<?php
$sku_code=$_REQUEST['product_sku'];
$where1=" WHERE 1 AND stock_available<=0";
$where1.=" AND `sku` = '$sku_code'";
$sql1="SELECT * FROM `ordercsv` $where1";
$readresult=$write->query($sql);

while ($row = $readresult->fetch() ) {
$product = Mage::getModel('catalog/product')->loadByAttribute('sku',$productId);
if($product){
?>
<tr>
    <td><?php echo $row['sku']; ?></td>
    <td><?php echo $row['manufacturer']; ?></td>
    <td><?php echo $row['product_name']; ?></td>
    <td><?php echo $product->getPrice(); ?></td>
    <!--<td>&nbsp;</td>-->
    <td><?php echo $row['order_id'];?></td>
    <td><?php echo $product->getAttributeText('color'); ?></td>
    <td><?php  $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($product); echo $stock->getQty(); 
	//print_r($stock->getData())
	
	?></td>
    <td><?php echo $row['quantity']; ?></td>
    
     <td><input type="text" name="update_qty[]" id="update_qty" value="" /></td>
   <td><input type="checkbox" name="chechkid[]" id="chechkid" value="<?php echo $row['ordercsv_id']; ?>" /></td>
<tr>
 <?php
 

  }
}?>

<table width="100%" border="0" cellspacing="3" cellpadding="3">
  <tr>
    <td width="33%">&nbsp;</td>
    <td width="2%">&nbsp;</td>
    <td width="65%">&nbsp;</td>
  </tr>
  <tr>
    <td align="right"><b><?php echo $this->__('Enter Stock Quantity:') ?></b></td>
    <td>&nbsp;</td>
    <td><input type="text" name="stock_enter_text" id="stock_enter_text" value=""/>


   </td>
  </tr>
  
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>
      <input type="submit" name="button2" id="button2" value="Submit">&nbsp;&nbsp;
      <!--<input type="submit" name="button2" id="button2" value="Order Process">--></td>
  <input type="hidden" name="current_url" value="<?php echo 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']; ?>" >
  <input type="hidden" name="flag" value="2" />
  </tr>
</table>

</form>
 	