<table width="100%" border="0" cellspacing="0" cellpadding="0">

  <tr>

    <td align="center"><h1><strong>osCommerce Products/Categories/Customers/Orders Import </strong></h1></td>

  </tr>

  <tr>

    <td><strong>Step 1. Configuration</strong></td>

  </tr>

  <tr>

    <td>Go to your <a href="<?php echo $this->getUrl()?>admin">Admin Secton</a> -&gt; Click &quot;System&quot; -&gt; Click &quot;Configuration&quot; -&gt; Click &quot;Configuration&quot; under letf menu &quot;osCommerce Import&quot;<br /><br />

</td>

  </tr>

  <tr>

    <td>
    <iframe width="560" height="315" src="http://www.youtube.com/embed/BuiR1SoJIfA" frameborder="0" allowfullscreen></iframe>
    <br /><br />
<br />

<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);  ?>Ezmage/OscommerceImport/step1.png" width="598" height="514" /></td>

  </tr>

  <tr>

    <td></td>

  </tr>

  <tr>

    <td><br />

    <br />

    <br />    <div align="center"><a href="<?php echo $this->getUrl('oscommerceimport')?>">Main Menu</a></div></td>

  </tr>

  <tr>

    <td>&nbsp;</td>

  </tr>

  <tr>

    <td><div align="center">Powered by <a href="http://www.ezmage.com/" target="_blank">ezMage</a> - We provide Magento Support 702-485-3332</div></td>

  </tr>

</table>

