<?php

	$conection_status = Mage::registry('conection_status');

	

?>

<table width="100%" border="0" cellspacing="0" cellpadding="0">

  <tr>

    <td align="center"><h1><strong>osCommerce Products/Categories/Customers/Orders Import </strong></h1></td>

  </tr>

  <tr>

    <td><strong>Step 3. Preparing TMP Tables</strong></td>

  </tr>

  <tr>

    <td><br /><br />

</td>

  </tr>

  <tr>

    <td>We will go to conect to the oscommerce database and read all the products id and categories id and save the information in the tmp tables</td>

  </tr>

  <tr>

    <td><br />

      <a href="<?php echo $this->getUrl('oscommerceimport/index/step31/')?>">Please click here to begin this proccess<br />

      <br /> </a>

      <br />

      <strong>Conection Status:</strong> <?php echo $conection_status; ?></td>

  </tr>

  <tr>

    <td><br />

    <br />

    <br />    <div align="center"><a href="<?php echo $this->getUrl('oscommerceimport')?>">Main Menu</a></div></td>

  </tr>

  <tr>

    <td>&nbsp;</td>

  </tr>

  <tr>

    <td><div align="center">Powered by <a href="http://www.ezmage.com/" target="_blank">ezMage</a> - We provide Magento Support 702-485-3332</div></td>

  </tr>

</table>

