<?php	
	//$importProductsTotal = Mage::getSingleton('core/session')->getimportProductsTotal();
	//$importedProductsTotal = Mage::getSingleton('core/session')->getimportedProductsTotal();	

?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center"><h1><strong>osCommerce Products/Categories/Customers/Orders Import </strong></h1></td>
  </tr>
  <tr>
    <td><strong>Step 8. Uninstall and Enjoy</strong></td>
  </tr>
  <tr>
    <td><br /><br />
</td>
  </tr>
  <tr>
    <td valign="top"><p>The import is done , please click the link below to remove the tmp tables and revome this extension</p>
      <p><a href="<?php echo $this->getUrl('oscommerceimport/index/step81/')?>">Delete TMP Tables</a>    
        <br />
        <br />
        <br />
    </p></td>
  </tr>
  <tr>
    <td valign="top"><div align="center"><h3>Need Help with Magento? Call us at 702-485-3332</h3></div></td>
  </tr>
  <tr>
    <td align="center" valign="top"><div align="center"></div></td>
  </tr>
  <tr>
    <td><br />
    <br />
    <br />    <div align="center"><a href="<?php echo $this->getUrl('oscommerceimport')?>">Main Menu</a></div></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><div align="center">Powered by <a href="http://www.ezmage.com/" target="_blank">ezMage</a> - We provide Magento Support 702-485-3332</div></td>
  </tr>
</table>